// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	discovery "github.com/nrc-no/core/api/pkg/apis/discovery"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*APIGroup)(nil), (*discovery.APIGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_APIGroup_To_discovery_APIGroup(a.(*APIGroup), b.(*discovery.APIGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*discovery.APIGroup)(nil), (*APIGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_discovery_APIGroup_To_v1_APIGroup(a.(*discovery.APIGroup), b.(*APIGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*APIGroupList)(nil), (*discovery.APIGroupList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_APIGroupList_To_discovery_APIGroupList(a.(*APIGroupList), b.(*discovery.APIGroupList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*discovery.APIGroupList)(nil), (*APIGroupList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_discovery_APIGroupList_To_v1_APIGroupList(a.(*discovery.APIGroupList), b.(*APIGroupList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*APIResource)(nil), (*discovery.APIResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_APIResource_To_discovery_APIResource(a.(*APIResource), b.(*discovery.APIResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*discovery.APIResource)(nil), (*APIResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_discovery_APIResource_To_v1_APIResource(a.(*discovery.APIResource), b.(*APIResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*APIResourceList)(nil), (*discovery.APIResourceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_APIResourceList_To_discovery_APIResourceList(a.(*APIResourceList), b.(*discovery.APIResourceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*discovery.APIResourceList)(nil), (*APIResourceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_discovery_APIResourceList_To_v1_APIResourceList(a.(*discovery.APIResourceList), b.(*APIResourceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*APIService)(nil), (*discovery.APIService)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_APIService_To_discovery_APIService(a.(*APIService), b.(*discovery.APIService), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*discovery.APIService)(nil), (*APIService)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_discovery_APIService_To_v1_APIService(a.(*discovery.APIService), b.(*APIService), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*APIServiceList)(nil), (*discovery.APIServiceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_APIServiceList_To_discovery_APIServiceList(a.(*APIServiceList), b.(*discovery.APIServiceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*discovery.APIServiceList)(nil), (*APIServiceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_discovery_APIServiceList_To_v1_APIServiceList(a.(*discovery.APIServiceList), b.(*APIServiceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*APIServiceSpec)(nil), (*discovery.APIServiceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_APIServiceSpec_To_discovery_APIServiceSpec(a.(*APIServiceSpec), b.(*discovery.APIServiceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*discovery.APIServiceSpec)(nil), (*APIServiceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_discovery_APIServiceSpec_To_v1_APIServiceSpec(a.(*discovery.APIServiceSpec), b.(*APIServiceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GroupVersionForDiscovery)(nil), (*discovery.GroupVersionForDiscovery)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_GroupVersionForDiscovery_To_discovery_GroupVersionForDiscovery(a.(*GroupVersionForDiscovery), b.(*discovery.GroupVersionForDiscovery), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*discovery.GroupVersionForDiscovery)(nil), (*GroupVersionForDiscovery)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_discovery_GroupVersionForDiscovery_To_v1_GroupVersionForDiscovery(a.(*discovery.GroupVersionForDiscovery), b.(*GroupVersionForDiscovery), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_APIGroup_To_discovery_APIGroup(in *APIGroup, out *discovery.APIGroup, s conversion.Scope) error {
	out.Name = in.Name
	out.Versions = *(*[]discovery.GroupVersionForDiscovery)(unsafe.Pointer(&in.Versions))
	if err := Convert_v1_GroupVersionForDiscovery_To_discovery_GroupVersionForDiscovery(&in.PreferredVersion, &out.PreferredVersion, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_APIGroup_To_discovery_APIGroup is an autogenerated conversion function.
func Convert_v1_APIGroup_To_discovery_APIGroup(in *APIGroup, out *discovery.APIGroup, s conversion.Scope) error {
	return autoConvert_v1_APIGroup_To_discovery_APIGroup(in, out, s)
}

func autoConvert_discovery_APIGroup_To_v1_APIGroup(in *discovery.APIGroup, out *APIGroup, s conversion.Scope) error {
	out.Name = in.Name
	out.Versions = *(*[]GroupVersionForDiscovery)(unsafe.Pointer(&in.Versions))
	if err := Convert_discovery_GroupVersionForDiscovery_To_v1_GroupVersionForDiscovery(&in.PreferredVersion, &out.PreferredVersion, s); err != nil {
		return err
	}
	return nil
}

// Convert_discovery_APIGroup_To_v1_APIGroup is an autogenerated conversion function.
func Convert_discovery_APIGroup_To_v1_APIGroup(in *discovery.APIGroup, out *APIGroup, s conversion.Scope) error {
	return autoConvert_discovery_APIGroup_To_v1_APIGroup(in, out, s)
}

func autoConvert_v1_APIGroupList_To_discovery_APIGroupList(in *APIGroupList, out *discovery.APIGroupList, s conversion.Scope) error {
	out.Groups = *(*[]discovery.APIGroup)(unsafe.Pointer(&in.Groups))
	return nil
}

// Convert_v1_APIGroupList_To_discovery_APIGroupList is an autogenerated conversion function.
func Convert_v1_APIGroupList_To_discovery_APIGroupList(in *APIGroupList, out *discovery.APIGroupList, s conversion.Scope) error {
	return autoConvert_v1_APIGroupList_To_discovery_APIGroupList(in, out, s)
}

func autoConvert_discovery_APIGroupList_To_v1_APIGroupList(in *discovery.APIGroupList, out *APIGroupList, s conversion.Scope) error {
	out.Groups = *(*[]APIGroup)(unsafe.Pointer(&in.Groups))
	return nil
}

// Convert_discovery_APIGroupList_To_v1_APIGroupList is an autogenerated conversion function.
func Convert_discovery_APIGroupList_To_v1_APIGroupList(in *discovery.APIGroupList, out *APIGroupList, s conversion.Scope) error {
	return autoConvert_discovery_APIGroupList_To_v1_APIGroupList(in, out, s)
}

func autoConvert_v1_APIResource_To_discovery_APIResource(in *APIResource, out *discovery.APIResource, s conversion.Scope) error {
	out.Name = in.Name
	out.SingularName = in.SingularName
	out.Namespaced = in.Namespaced
	out.Group = in.Group
	out.Version = in.Version
	out.Kind = in.Kind
	out.Verbs = *(*discovery.Verbs)(unsafe.Pointer(&in.Verbs))
	return nil
}

// Convert_v1_APIResource_To_discovery_APIResource is an autogenerated conversion function.
func Convert_v1_APIResource_To_discovery_APIResource(in *APIResource, out *discovery.APIResource, s conversion.Scope) error {
	return autoConvert_v1_APIResource_To_discovery_APIResource(in, out, s)
}

func autoConvert_discovery_APIResource_To_v1_APIResource(in *discovery.APIResource, out *APIResource, s conversion.Scope) error {
	out.Name = in.Name
	out.SingularName = in.SingularName
	out.Namespaced = in.Namespaced
	out.Group = in.Group
	out.Version = in.Version
	out.Kind = in.Kind
	out.Verbs = *(*Verbs)(unsafe.Pointer(&in.Verbs))
	return nil
}

// Convert_discovery_APIResource_To_v1_APIResource is an autogenerated conversion function.
func Convert_discovery_APIResource_To_v1_APIResource(in *discovery.APIResource, out *APIResource, s conversion.Scope) error {
	return autoConvert_discovery_APIResource_To_v1_APIResource(in, out, s)
}

func autoConvert_v1_APIResourceList_To_discovery_APIResourceList(in *APIResourceList, out *discovery.APIResourceList, s conversion.Scope) error {
	out.GroupVersion = in.GroupVersion
	out.APIResources = *(*[]discovery.APIResource)(unsafe.Pointer(&in.APIResources))
	return nil
}

// Convert_v1_APIResourceList_To_discovery_APIResourceList is an autogenerated conversion function.
func Convert_v1_APIResourceList_To_discovery_APIResourceList(in *APIResourceList, out *discovery.APIResourceList, s conversion.Scope) error {
	return autoConvert_v1_APIResourceList_To_discovery_APIResourceList(in, out, s)
}

func autoConvert_discovery_APIResourceList_To_v1_APIResourceList(in *discovery.APIResourceList, out *APIResourceList, s conversion.Scope) error {
	out.GroupVersion = in.GroupVersion
	out.APIResources = *(*[]APIResource)(unsafe.Pointer(&in.APIResources))
	return nil
}

// Convert_discovery_APIResourceList_To_v1_APIResourceList is an autogenerated conversion function.
func Convert_discovery_APIResourceList_To_v1_APIResourceList(in *discovery.APIResourceList, out *APIResourceList, s conversion.Scope) error {
	return autoConvert_discovery_APIResourceList_To_v1_APIResourceList(in, out, s)
}

func autoConvert_v1_APIService_To_discovery_APIService(in *APIService, out *discovery.APIService, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_APIServiceSpec_To_discovery_APIServiceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_APIService_To_discovery_APIService is an autogenerated conversion function.
func Convert_v1_APIService_To_discovery_APIService(in *APIService, out *discovery.APIService, s conversion.Scope) error {
	return autoConvert_v1_APIService_To_discovery_APIService(in, out, s)
}

func autoConvert_discovery_APIService_To_v1_APIService(in *discovery.APIService, out *APIService, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_discovery_APIServiceSpec_To_v1_APIServiceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_discovery_APIService_To_v1_APIService is an autogenerated conversion function.
func Convert_discovery_APIService_To_v1_APIService(in *discovery.APIService, out *APIService, s conversion.Scope) error {
	return autoConvert_discovery_APIService_To_v1_APIService(in, out, s)
}

func autoConvert_v1_APIServiceList_To_discovery_APIServiceList(in *APIServiceList, out *discovery.APIServiceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]discovery.APIService)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_APIServiceList_To_discovery_APIServiceList is an autogenerated conversion function.
func Convert_v1_APIServiceList_To_discovery_APIServiceList(in *APIServiceList, out *discovery.APIServiceList, s conversion.Scope) error {
	return autoConvert_v1_APIServiceList_To_discovery_APIServiceList(in, out, s)
}

func autoConvert_discovery_APIServiceList_To_v1_APIServiceList(in *discovery.APIServiceList, out *APIServiceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]APIService)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_discovery_APIServiceList_To_v1_APIServiceList is an autogenerated conversion function.
func Convert_discovery_APIServiceList_To_v1_APIServiceList(in *discovery.APIServiceList, out *APIServiceList, s conversion.Scope) error {
	return autoConvert_discovery_APIServiceList_To_v1_APIServiceList(in, out, s)
}

func autoConvert_v1_APIServiceSpec_To_discovery_APIServiceSpec(in *APIServiceSpec, out *discovery.APIServiceSpec, s conversion.Scope) error {
	out.Group = in.Group
	out.Version = in.Version
	return nil
}

// Convert_v1_APIServiceSpec_To_discovery_APIServiceSpec is an autogenerated conversion function.
func Convert_v1_APIServiceSpec_To_discovery_APIServiceSpec(in *APIServiceSpec, out *discovery.APIServiceSpec, s conversion.Scope) error {
	return autoConvert_v1_APIServiceSpec_To_discovery_APIServiceSpec(in, out, s)
}

func autoConvert_discovery_APIServiceSpec_To_v1_APIServiceSpec(in *discovery.APIServiceSpec, out *APIServiceSpec, s conversion.Scope) error {
	out.Group = in.Group
	out.Version = in.Version
	return nil
}

// Convert_discovery_APIServiceSpec_To_v1_APIServiceSpec is an autogenerated conversion function.
func Convert_discovery_APIServiceSpec_To_v1_APIServiceSpec(in *discovery.APIServiceSpec, out *APIServiceSpec, s conversion.Scope) error {
	return autoConvert_discovery_APIServiceSpec_To_v1_APIServiceSpec(in, out, s)
}

func autoConvert_v1_GroupVersionForDiscovery_To_discovery_GroupVersionForDiscovery(in *GroupVersionForDiscovery, out *discovery.GroupVersionForDiscovery, s conversion.Scope) error {
	out.GroupVersion = in.GroupVersion
	out.Version = in.Version
	return nil
}

// Convert_v1_GroupVersionForDiscovery_To_discovery_GroupVersionForDiscovery is an autogenerated conversion function.
func Convert_v1_GroupVersionForDiscovery_To_discovery_GroupVersionForDiscovery(in *GroupVersionForDiscovery, out *discovery.GroupVersionForDiscovery, s conversion.Scope) error {
	return autoConvert_v1_GroupVersionForDiscovery_To_discovery_GroupVersionForDiscovery(in, out, s)
}

func autoConvert_discovery_GroupVersionForDiscovery_To_v1_GroupVersionForDiscovery(in *discovery.GroupVersionForDiscovery, out *GroupVersionForDiscovery, s conversion.Scope) error {
	out.GroupVersion = in.GroupVersion
	out.Version = in.Version
	return nil
}

// Convert_discovery_GroupVersionForDiscovery_To_v1_GroupVersionForDiscovery is an autogenerated conversion function.
func Convert_discovery_GroupVersionForDiscovery_To_v1_GroupVersionForDiscovery(in *discovery.GroupVersionForDiscovery, out *GroupVersionForDiscovery, s conversion.Scope) error {
	return autoConvert_discovery_GroupVersionForDiscovery_To_v1_GroupVersionForDiscovery(in, out, s)
}
