// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	core "github.com/nrc-no/coreapi/pkg/apis/core"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*FormDefinition)(nil), (*core.FormDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FormDefinition_To_core_FormDefinition(a.(*FormDefinition), b.(*core.FormDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormDefinition)(nil), (*FormDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormDefinition_To_v1_FormDefinition(a.(*core.FormDefinition), b.(*FormDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FormDefinitionList)(nil), (*core.FormDefinitionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FormDefinitionList_To_core_FormDefinitionList(a.(*FormDefinitionList), b.(*core.FormDefinitionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormDefinitionList)(nil), (*FormDefinitionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormDefinitionList_To_v1_FormDefinitionList(a.(*core.FormDefinitionList), b.(*FormDefinitionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FormDefinitionNames)(nil), (*core.FormDefinitionNames)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FormDefinitionNames_To_core_FormDefinitionNames(a.(*FormDefinitionNames), b.(*core.FormDefinitionNames), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormDefinitionNames)(nil), (*FormDefinitionNames)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormDefinitionNames_To_v1_FormDefinitionNames(a.(*core.FormDefinitionNames), b.(*FormDefinitionNames), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FormDefinitionSchema)(nil), (*core.FormDefinitionSchema)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FormDefinitionSchema_To_core_FormDefinitionSchema(a.(*FormDefinitionSchema), b.(*core.FormDefinitionSchema), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormDefinitionSchema)(nil), (*FormDefinitionSchema)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormDefinitionSchema_To_v1_FormDefinitionSchema(a.(*core.FormDefinitionSchema), b.(*FormDefinitionSchema), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FormDefinitionSpec)(nil), (*core.FormDefinitionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FormDefinitionSpec_To_core_FormDefinitionSpec(a.(*FormDefinitionSpec), b.(*core.FormDefinitionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormDefinitionSpec)(nil), (*FormDefinitionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormDefinitionSpec_To_v1_FormDefinitionSpec(a.(*core.FormDefinitionSpec), b.(*FormDefinitionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FormDefinitionValidation)(nil), (*core.FormDefinitionValidation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FormDefinitionValidation_To_core_FormDefinitionValidation(a.(*FormDefinitionValidation), b.(*core.FormDefinitionValidation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormDefinitionValidation)(nil), (*FormDefinitionValidation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormDefinitionValidation_To_v1_FormDefinitionValidation(a.(*core.FormDefinitionValidation), b.(*FormDefinitionValidation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FormDefinitionVersion)(nil), (*core.FormDefinitionVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FormDefinitionVersion_To_core_FormDefinitionVersion(a.(*FormDefinitionVersion), b.(*core.FormDefinitionVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormDefinitionVersion)(nil), (*FormDefinitionVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormDefinitionVersion_To_v1_FormDefinitionVersion(a.(*core.FormDefinitionVersion), b.(*FormDefinitionVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FormElementDefinition)(nil), (*core.FormElementDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FormElementDefinition_To_core_FormElementDefinition(a.(*FormElementDefinition), b.(*core.FormElementDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormElementDefinition)(nil), (*FormElementDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormElementDefinition_To_v1_FormElementDefinition(a.(*core.FormElementDefinition), b.(*FormElementDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TranslatedString)(nil), (*core.TranslatedString)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_TranslatedString_To_core_TranslatedString(a.(*TranslatedString), b.(*core.TranslatedString), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.TranslatedString)(nil), (*TranslatedString)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_TranslatedString_To_v1_TranslatedString(a.(*core.TranslatedString), b.(*TranslatedString), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_FormDefinition_To_core_FormDefinition(in *FormDefinition, out *core.FormDefinition, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_FormDefinitionSpec_To_core_FormDefinitionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_FormDefinition_To_core_FormDefinition is an autogenerated conversion function.
func Convert_v1_FormDefinition_To_core_FormDefinition(in *FormDefinition, out *core.FormDefinition, s conversion.Scope) error {
	return autoConvert_v1_FormDefinition_To_core_FormDefinition(in, out, s)
}

func autoConvert_core_FormDefinition_To_v1_FormDefinition(in *core.FormDefinition, out *FormDefinition, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_core_FormDefinitionSpec_To_v1_FormDefinitionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_FormDefinition_To_v1_FormDefinition is an autogenerated conversion function.
func Convert_core_FormDefinition_To_v1_FormDefinition(in *core.FormDefinition, out *FormDefinition, s conversion.Scope) error {
	return autoConvert_core_FormDefinition_To_v1_FormDefinition(in, out, s)
}

func autoConvert_v1_FormDefinitionList_To_core_FormDefinitionList(in *FormDefinitionList, out *core.FormDefinitionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]core.FormDefinition)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_FormDefinitionList_To_core_FormDefinitionList is an autogenerated conversion function.
func Convert_v1_FormDefinitionList_To_core_FormDefinitionList(in *FormDefinitionList, out *core.FormDefinitionList, s conversion.Scope) error {
	return autoConvert_v1_FormDefinitionList_To_core_FormDefinitionList(in, out, s)
}

func autoConvert_core_FormDefinitionList_To_v1_FormDefinitionList(in *core.FormDefinitionList, out *FormDefinitionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]FormDefinition)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_core_FormDefinitionList_To_v1_FormDefinitionList is an autogenerated conversion function.
func Convert_core_FormDefinitionList_To_v1_FormDefinitionList(in *core.FormDefinitionList, out *FormDefinitionList, s conversion.Scope) error {
	return autoConvert_core_FormDefinitionList_To_v1_FormDefinitionList(in, out, s)
}

func autoConvert_v1_FormDefinitionNames_To_core_FormDefinitionNames(in *FormDefinitionNames, out *core.FormDefinitionNames, s conversion.Scope) error {
	out.Plural = in.Plural
	out.Singular = in.Singular
	out.Kind = in.Kind
	return nil
}

// Convert_v1_FormDefinitionNames_To_core_FormDefinitionNames is an autogenerated conversion function.
func Convert_v1_FormDefinitionNames_To_core_FormDefinitionNames(in *FormDefinitionNames, out *core.FormDefinitionNames, s conversion.Scope) error {
	return autoConvert_v1_FormDefinitionNames_To_core_FormDefinitionNames(in, out, s)
}

func autoConvert_core_FormDefinitionNames_To_v1_FormDefinitionNames(in *core.FormDefinitionNames, out *FormDefinitionNames, s conversion.Scope) error {
	out.Plural = in.Plural
	out.Singular = in.Singular
	out.Kind = in.Kind
	return nil
}

// Convert_core_FormDefinitionNames_To_v1_FormDefinitionNames is an autogenerated conversion function.
func Convert_core_FormDefinitionNames_To_v1_FormDefinitionNames(in *core.FormDefinitionNames, out *FormDefinitionNames, s conversion.Scope) error {
	return autoConvert_core_FormDefinitionNames_To_v1_FormDefinitionNames(in, out, s)
}

func autoConvert_v1_FormDefinitionSchema_To_core_FormDefinitionSchema(in *FormDefinitionSchema, out *core.FormDefinitionSchema, s conversion.Scope) error {
	if err := Convert_v1_FormElementDefinition_To_core_FormElementDefinition(&in.Root, &out.Root, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_FormDefinitionSchema_To_core_FormDefinitionSchema is an autogenerated conversion function.
func Convert_v1_FormDefinitionSchema_To_core_FormDefinitionSchema(in *FormDefinitionSchema, out *core.FormDefinitionSchema, s conversion.Scope) error {
	return autoConvert_v1_FormDefinitionSchema_To_core_FormDefinitionSchema(in, out, s)
}

func autoConvert_core_FormDefinitionSchema_To_v1_FormDefinitionSchema(in *core.FormDefinitionSchema, out *FormDefinitionSchema, s conversion.Scope) error {
	if err := Convert_core_FormElementDefinition_To_v1_FormElementDefinition(&in.Root, &out.Root, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_FormDefinitionSchema_To_v1_FormDefinitionSchema is an autogenerated conversion function.
func Convert_core_FormDefinitionSchema_To_v1_FormDefinitionSchema(in *core.FormDefinitionSchema, out *FormDefinitionSchema, s conversion.Scope) error {
	return autoConvert_core_FormDefinitionSchema_To_v1_FormDefinitionSchema(in, out, s)
}

func autoConvert_v1_FormDefinitionSpec_To_core_FormDefinitionSpec(in *FormDefinitionSpec, out *core.FormDefinitionSpec, s conversion.Scope) error {
	out.Group = in.Group
	if err := Convert_v1_FormDefinitionNames_To_core_FormDefinitionNames(&in.Names, &out.Names, s); err != nil {
		return err
	}
	out.Versions = *(*[]core.FormDefinitionVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_v1_FormDefinitionSpec_To_core_FormDefinitionSpec is an autogenerated conversion function.
func Convert_v1_FormDefinitionSpec_To_core_FormDefinitionSpec(in *FormDefinitionSpec, out *core.FormDefinitionSpec, s conversion.Scope) error {
	return autoConvert_v1_FormDefinitionSpec_To_core_FormDefinitionSpec(in, out, s)
}

func autoConvert_core_FormDefinitionSpec_To_v1_FormDefinitionSpec(in *core.FormDefinitionSpec, out *FormDefinitionSpec, s conversion.Scope) error {
	out.Group = in.Group
	if err := Convert_core_FormDefinitionNames_To_v1_FormDefinitionNames(&in.Names, &out.Names, s); err != nil {
		return err
	}
	out.Versions = *(*[]FormDefinitionVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_core_FormDefinitionSpec_To_v1_FormDefinitionSpec is an autogenerated conversion function.
func Convert_core_FormDefinitionSpec_To_v1_FormDefinitionSpec(in *core.FormDefinitionSpec, out *FormDefinitionSpec, s conversion.Scope) error {
	return autoConvert_core_FormDefinitionSpec_To_v1_FormDefinitionSpec(in, out, s)
}

func autoConvert_v1_FormDefinitionValidation_To_core_FormDefinitionValidation(in *FormDefinitionValidation, out *core.FormDefinitionValidation, s conversion.Scope) error {
	if err := Convert_v1_FormDefinitionSchema_To_core_FormDefinitionSchema(&in.FormSchema, &out.FormSchema, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_FormDefinitionValidation_To_core_FormDefinitionValidation is an autogenerated conversion function.
func Convert_v1_FormDefinitionValidation_To_core_FormDefinitionValidation(in *FormDefinitionValidation, out *core.FormDefinitionValidation, s conversion.Scope) error {
	return autoConvert_v1_FormDefinitionValidation_To_core_FormDefinitionValidation(in, out, s)
}

func autoConvert_core_FormDefinitionValidation_To_v1_FormDefinitionValidation(in *core.FormDefinitionValidation, out *FormDefinitionValidation, s conversion.Scope) error {
	if err := Convert_core_FormDefinitionSchema_To_v1_FormDefinitionSchema(&in.FormSchema, &out.FormSchema, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_FormDefinitionValidation_To_v1_FormDefinitionValidation is an autogenerated conversion function.
func Convert_core_FormDefinitionValidation_To_v1_FormDefinitionValidation(in *core.FormDefinitionValidation, out *FormDefinitionValidation, s conversion.Scope) error {
	return autoConvert_core_FormDefinitionValidation_To_v1_FormDefinitionValidation(in, out, s)
}

func autoConvert_v1_FormDefinitionVersion_To_core_FormDefinitionVersion(in *FormDefinitionVersion, out *core.FormDefinitionVersion, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_v1_FormDefinitionValidation_To_core_FormDefinitionValidation(&in.Schema, &out.Schema, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_FormDefinitionVersion_To_core_FormDefinitionVersion is an autogenerated conversion function.
func Convert_v1_FormDefinitionVersion_To_core_FormDefinitionVersion(in *FormDefinitionVersion, out *core.FormDefinitionVersion, s conversion.Scope) error {
	return autoConvert_v1_FormDefinitionVersion_To_core_FormDefinitionVersion(in, out, s)
}

func autoConvert_core_FormDefinitionVersion_To_v1_FormDefinitionVersion(in *core.FormDefinitionVersion, out *FormDefinitionVersion, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_core_FormDefinitionValidation_To_v1_FormDefinitionValidation(&in.Schema, &out.Schema, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_FormDefinitionVersion_To_v1_FormDefinitionVersion is an autogenerated conversion function.
func Convert_core_FormDefinitionVersion_To_v1_FormDefinitionVersion(in *core.FormDefinitionVersion, out *FormDefinitionVersion, s conversion.Scope) error {
	return autoConvert_core_FormDefinitionVersion_To_v1_FormDefinitionVersion(in, out, s)
}

func autoConvert_v1_FormElementDefinition_To_core_FormElementDefinition(in *FormElementDefinition, out *core.FormElementDefinition, s conversion.Scope) error {
	out.Key = in.Key
	out.Name = *(*core.TranslatedStrings)(unsafe.Pointer(&in.Name))
	out.Description = *(*core.TranslatedStrings)(unsafe.Pointer(&in.Description))
	out.Help = *(*core.TranslatedStrings)(unsafe.Pointer(&in.Help))
	out.Type = core.FormElementType(in.Type)
	out.Required = in.Required
	out.Children = *(*[]core.FormElementDefinition)(unsafe.Pointer(&in.Children))
	return nil
}

// Convert_v1_FormElementDefinition_To_core_FormElementDefinition is an autogenerated conversion function.
func Convert_v1_FormElementDefinition_To_core_FormElementDefinition(in *FormElementDefinition, out *core.FormElementDefinition, s conversion.Scope) error {
	return autoConvert_v1_FormElementDefinition_To_core_FormElementDefinition(in, out, s)
}

func autoConvert_core_FormElementDefinition_To_v1_FormElementDefinition(in *core.FormElementDefinition, out *FormElementDefinition, s conversion.Scope) error {
	out.Key = in.Key
	out.Name = *(*TranslatedStrings)(unsafe.Pointer(&in.Name))
	out.Description = *(*TranslatedStrings)(unsafe.Pointer(&in.Description))
	out.Help = *(*TranslatedStrings)(unsafe.Pointer(&in.Help))
	out.Type = FormElementType(in.Type)
	out.Required = in.Required
	out.Children = *(*[]FormElementDefinition)(unsafe.Pointer(&in.Children))
	return nil
}

// Convert_core_FormElementDefinition_To_v1_FormElementDefinition is an autogenerated conversion function.
func Convert_core_FormElementDefinition_To_v1_FormElementDefinition(in *core.FormElementDefinition, out *FormElementDefinition, s conversion.Scope) error {
	return autoConvert_core_FormElementDefinition_To_v1_FormElementDefinition(in, out, s)
}

func autoConvert_v1_TranslatedString_To_core_TranslatedString(in *TranslatedString, out *core.TranslatedString, s conversion.Scope) error {
	out.Locale = in.Locale
	out.Value = in.Value
	return nil
}

// Convert_v1_TranslatedString_To_core_TranslatedString is an autogenerated conversion function.
func Convert_v1_TranslatedString_To_core_TranslatedString(in *TranslatedString, out *core.TranslatedString, s conversion.Scope) error {
	return autoConvert_v1_TranslatedString_To_core_TranslatedString(in, out, s)
}

func autoConvert_core_TranslatedString_To_v1_TranslatedString(in *core.TranslatedString, out *TranslatedString, s conversion.Scope) error {
	out.Locale = in.Locale
	out.Value = in.Value
	return nil
}

// Convert_core_TranslatedString_To_v1_TranslatedString is an autogenerated conversion function.
func Convert_core_TranslatedString_To_v1_TranslatedString(in *core.TranslatedString, out *TranslatedString, s conversion.Scope) error {
	return autoConvert_core_TranslatedString_To_v1_TranslatedString(in, out, s)
}
