// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	core "github.com/nrc-no/core/api/pkg/apis/core"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AdditionalBeneficiaryInformation)(nil), (*core.AdditionalBeneficiaryInformation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_AdditionalBeneficiaryInformation_To_core_AdditionalBeneficiaryInformation(a.(*AdditionalBeneficiaryInformation), b.(*core.AdditionalBeneficiaryInformation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.AdditionalBeneficiaryInformation)(nil), (*AdditionalBeneficiaryInformation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_AdditionalBeneficiaryInformation_To_v1_AdditionalBeneficiaryInformation(a.(*core.AdditionalBeneficiaryInformation), b.(*AdditionalBeneficiaryInformation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CustomResourceDefinition)(nil), (*core.CustomResourceDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CustomResourceDefinition_To_core_CustomResourceDefinition(a.(*CustomResourceDefinition), b.(*core.CustomResourceDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.CustomResourceDefinition)(nil), (*CustomResourceDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_CustomResourceDefinition_To_v1_CustomResourceDefinition(a.(*core.CustomResourceDefinition), b.(*CustomResourceDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CustomResourceDefinitionList)(nil), (*core.CustomResourceDefinitionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CustomResourceDefinitionList_To_core_CustomResourceDefinitionList(a.(*CustomResourceDefinitionList), b.(*core.CustomResourceDefinitionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.CustomResourceDefinitionList)(nil), (*CustomResourceDefinitionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_CustomResourceDefinitionList_To_v1_CustomResourceDefinitionList(a.(*core.CustomResourceDefinitionList), b.(*CustomResourceDefinitionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CustomResourceDefinitionNames)(nil), (*core.CustomResourceDefinitionNames)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CustomResourceDefinitionNames_To_core_CustomResourceDefinitionNames(a.(*CustomResourceDefinitionNames), b.(*core.CustomResourceDefinitionNames), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.CustomResourceDefinitionNames)(nil), (*CustomResourceDefinitionNames)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_CustomResourceDefinitionNames_To_v1_CustomResourceDefinitionNames(a.(*core.CustomResourceDefinitionNames), b.(*CustomResourceDefinitionNames), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CustomResourceDefinitionSpec)(nil), (*core.CustomResourceDefinitionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CustomResourceDefinitionSpec_To_core_CustomResourceDefinitionSpec(a.(*CustomResourceDefinitionSpec), b.(*core.CustomResourceDefinitionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.CustomResourceDefinitionSpec)(nil), (*CustomResourceDefinitionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_CustomResourceDefinitionSpec_To_v1_CustomResourceDefinitionSpec(a.(*core.CustomResourceDefinitionSpec), b.(*CustomResourceDefinitionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CustomResourceDefinitionValidation)(nil), (*core.CustomResourceDefinitionValidation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CustomResourceDefinitionValidation_To_core_CustomResourceDefinitionValidation(a.(*CustomResourceDefinitionValidation), b.(*core.CustomResourceDefinitionValidation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.CustomResourceDefinitionValidation)(nil), (*CustomResourceDefinitionValidation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_CustomResourceDefinitionValidation_To_v1_CustomResourceDefinitionValidation(a.(*core.CustomResourceDefinitionValidation), b.(*CustomResourceDefinitionValidation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CustomResourceDefinitionVersion)(nil), (*core.CustomResourceDefinitionVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CustomResourceDefinitionVersion_To_core_CustomResourceDefinitionVersion(a.(*CustomResourceDefinitionVersion), b.(*core.CustomResourceDefinitionVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.CustomResourceDefinitionVersion)(nil), (*CustomResourceDefinitionVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_CustomResourceDefinitionVersion_To_v1_CustomResourceDefinitionVersion(a.(*core.CustomResourceDefinitionVersion), b.(*CustomResourceDefinitionVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExternalDocumentation)(nil), (*core.ExternalDocumentation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ExternalDocumentation_To_core_ExternalDocumentation(a.(*ExternalDocumentation), b.(*core.ExternalDocumentation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ExternalDocumentation)(nil), (*ExternalDocumentation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ExternalDocumentation_To_v1_ExternalDocumentation(a.(*core.ExternalDocumentation), b.(*ExternalDocumentation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FormDefinition)(nil), (*core.FormDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FormDefinition_To_core_FormDefinition(a.(*FormDefinition), b.(*core.FormDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormDefinition)(nil), (*FormDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormDefinition_To_v1_FormDefinition(a.(*core.FormDefinition), b.(*FormDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FormDefinitionList)(nil), (*core.FormDefinitionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FormDefinitionList_To_core_FormDefinitionList(a.(*FormDefinitionList), b.(*core.FormDefinitionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormDefinitionList)(nil), (*FormDefinitionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormDefinitionList_To_v1_FormDefinitionList(a.(*core.FormDefinitionList), b.(*FormDefinitionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FormDefinitionNames)(nil), (*core.FormDefinitionNames)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FormDefinitionNames_To_core_FormDefinitionNames(a.(*FormDefinitionNames), b.(*core.FormDefinitionNames), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormDefinitionNames)(nil), (*FormDefinitionNames)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormDefinitionNames_To_v1_FormDefinitionNames(a.(*core.FormDefinitionNames), b.(*FormDefinitionNames), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FormDefinitionSchema)(nil), (*core.FormDefinitionSchema)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FormDefinitionSchema_To_core_FormDefinitionSchema(a.(*FormDefinitionSchema), b.(*core.FormDefinitionSchema), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormDefinitionSchema)(nil), (*FormDefinitionSchema)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormDefinitionSchema_To_v1_FormDefinitionSchema(a.(*core.FormDefinitionSchema), b.(*FormDefinitionSchema), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FormDefinitionSpec)(nil), (*core.FormDefinitionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FormDefinitionSpec_To_core_FormDefinitionSpec(a.(*FormDefinitionSpec), b.(*core.FormDefinitionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormDefinitionSpec)(nil), (*FormDefinitionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormDefinitionSpec_To_v1_FormDefinitionSpec(a.(*core.FormDefinitionSpec), b.(*FormDefinitionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FormDefinitionValidation)(nil), (*core.FormDefinitionValidation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FormDefinitionValidation_To_core_FormDefinitionValidation(a.(*FormDefinitionValidation), b.(*core.FormDefinitionValidation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormDefinitionValidation)(nil), (*FormDefinitionValidation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormDefinitionValidation_To_v1_FormDefinitionValidation(a.(*core.FormDefinitionValidation), b.(*FormDefinitionValidation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FormDefinitionVersion)(nil), (*core.FormDefinitionVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FormDefinitionVersion_To_core_FormDefinitionVersion(a.(*FormDefinitionVersion), b.(*core.FormDefinitionVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormDefinitionVersion)(nil), (*FormDefinitionVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormDefinitionVersion_To_v1_FormDefinitionVersion(a.(*core.FormDefinitionVersion), b.(*FormDefinitionVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FormElementDefinition)(nil), (*core.FormElementDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FormElementDefinition_To_core_FormElementDefinition(a.(*FormElementDefinition), b.(*core.FormElementDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormElementDefinition)(nil), (*FormElementDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormElementDefinition_To_v1_FormElementDefinition(a.(*core.FormElementDefinition), b.(*FormElementDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*JSON)(nil), (*core.JSON)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_JSON_To_core_JSON(a.(*JSON), b.(*core.JSON), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.JSON)(nil), (*JSON)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_JSON_To_v1_JSON(a.(*core.JSON), b.(*JSON), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*JSONSchemaProps)(nil), (*core.JSONSchemaProps)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_JSONSchemaProps_To_core_JSONSchemaProps(a.(*JSONSchemaProps), b.(*core.JSONSchemaProps), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.JSONSchemaProps)(nil), (*JSONSchemaProps)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_JSONSchemaProps_To_v1_JSONSchemaProps(a.(*core.JSONSchemaProps), b.(*JSONSchemaProps), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*JSONSchemaPropsOrArray)(nil), (*core.JSONSchemaPropsOrArray)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_JSONSchemaPropsOrArray_To_core_JSONSchemaPropsOrArray(a.(*JSONSchemaPropsOrArray), b.(*core.JSONSchemaPropsOrArray), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.JSONSchemaPropsOrArray)(nil), (*JSONSchemaPropsOrArray)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_JSONSchemaPropsOrArray_To_v1_JSONSchemaPropsOrArray(a.(*core.JSONSchemaPropsOrArray), b.(*JSONSchemaPropsOrArray), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*JSONSchemaPropsOrBool)(nil), (*core.JSONSchemaPropsOrBool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_JSONSchemaPropsOrBool_To_core_JSONSchemaPropsOrBool(a.(*JSONSchemaPropsOrBool), b.(*core.JSONSchemaPropsOrBool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.JSONSchemaPropsOrBool)(nil), (*JSONSchemaPropsOrBool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_JSONSchemaPropsOrBool_To_v1_JSONSchemaPropsOrBool(a.(*core.JSONSchemaPropsOrBool), b.(*JSONSchemaPropsOrBool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*JSONSchemaPropsOrStringArray)(nil), (*core.JSONSchemaPropsOrStringArray)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_JSONSchemaPropsOrStringArray_To_core_JSONSchemaPropsOrStringArray(a.(*JSONSchemaPropsOrStringArray), b.(*core.JSONSchemaPropsOrStringArray), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.JSONSchemaPropsOrStringArray)(nil), (*JSONSchemaPropsOrStringArray)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_JSONSchemaPropsOrStringArray_To_v1_JSONSchemaPropsOrStringArray(a.(*core.JSONSchemaPropsOrStringArray), b.(*JSONSchemaPropsOrStringArray), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OperatingScope)(nil), (*core.OperatingScope)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_OperatingScope_To_core_OperatingScope(a.(*OperatingScope), b.(*core.OperatingScope), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.OperatingScope)(nil), (*OperatingScope)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_OperatingScope_To_v1_OperatingScope(a.(*core.OperatingScope), b.(*OperatingScope), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OperatingScopeList)(nil), (*core.OperatingScopeList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_OperatingScopeList_To_core_OperatingScopeList(a.(*OperatingScopeList), b.(*core.OperatingScopeList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.OperatingScopeList)(nil), (*OperatingScopeList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_OperatingScopeList_To_v1_OperatingScopeList(a.(*core.OperatingScopeList), b.(*OperatingScopeList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OperatingScopeSpec)(nil), (*core.OperatingScopeSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_OperatingScopeSpec_To_core_OperatingScopeSpec(a.(*OperatingScopeSpec), b.(*core.OperatingScopeSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.OperatingScopeSpec)(nil), (*OperatingScopeSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_OperatingScopeSpec_To_v1_OperatingScopeSpec(a.(*core.OperatingScopeSpec), b.(*OperatingScopeSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TranslatedString)(nil), (*core.TranslatedString)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_TranslatedString_To_core_TranslatedString(a.(*TranslatedString), b.(*core.TranslatedString), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.TranslatedString)(nil), (*TranslatedString)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_TranslatedString_To_v1_TranslatedString(a.(*core.TranslatedString), b.(*TranslatedString), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*User)(nil), (*core.User)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_User_To_core_User(a.(*User), b.(*core.User), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.User)(nil), (*User)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_User_To_v1_User(a.(*core.User), b.(*User), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UserList)(nil), (*core.UserList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_UserList_To_core_UserList(a.(*UserList), b.(*core.UserList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.UserList)(nil), (*UserList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_UserList_To_v1_UserList(a.(*core.UserList), b.(*UserList), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_AdditionalBeneficiaryInformation_To_core_AdditionalBeneficiaryInformation(in *AdditionalBeneficiaryInformation, out *core.AdditionalBeneficiaryInformation, s conversion.Scope) error {
	out.Key = in.Key
	out.Type = in.Type
	return nil
}

// Convert_v1_AdditionalBeneficiaryInformation_To_core_AdditionalBeneficiaryInformation is an autogenerated conversion function.
func Convert_v1_AdditionalBeneficiaryInformation_To_core_AdditionalBeneficiaryInformation(in *AdditionalBeneficiaryInformation, out *core.AdditionalBeneficiaryInformation, s conversion.Scope) error {
	return autoConvert_v1_AdditionalBeneficiaryInformation_To_core_AdditionalBeneficiaryInformation(in, out, s)
}

func autoConvert_core_AdditionalBeneficiaryInformation_To_v1_AdditionalBeneficiaryInformation(in *core.AdditionalBeneficiaryInformation, out *AdditionalBeneficiaryInformation, s conversion.Scope) error {
	out.Key = in.Key
	out.Type = in.Type
	return nil
}

// Convert_core_AdditionalBeneficiaryInformation_To_v1_AdditionalBeneficiaryInformation is an autogenerated conversion function.
func Convert_core_AdditionalBeneficiaryInformation_To_v1_AdditionalBeneficiaryInformation(in *core.AdditionalBeneficiaryInformation, out *AdditionalBeneficiaryInformation, s conversion.Scope) error {
	return autoConvert_core_AdditionalBeneficiaryInformation_To_v1_AdditionalBeneficiaryInformation(in, out, s)
}

func autoConvert_v1_CustomResourceDefinition_To_core_CustomResourceDefinition(in *CustomResourceDefinition, out *core.CustomResourceDefinition, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_CustomResourceDefinitionSpec_To_core_CustomResourceDefinitionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_CustomResourceDefinition_To_core_CustomResourceDefinition is an autogenerated conversion function.
func Convert_v1_CustomResourceDefinition_To_core_CustomResourceDefinition(in *CustomResourceDefinition, out *core.CustomResourceDefinition, s conversion.Scope) error {
	return autoConvert_v1_CustomResourceDefinition_To_core_CustomResourceDefinition(in, out, s)
}

func autoConvert_core_CustomResourceDefinition_To_v1_CustomResourceDefinition(in *core.CustomResourceDefinition, out *CustomResourceDefinition, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_core_CustomResourceDefinitionSpec_To_v1_CustomResourceDefinitionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_CustomResourceDefinition_To_v1_CustomResourceDefinition is an autogenerated conversion function.
func Convert_core_CustomResourceDefinition_To_v1_CustomResourceDefinition(in *core.CustomResourceDefinition, out *CustomResourceDefinition, s conversion.Scope) error {
	return autoConvert_core_CustomResourceDefinition_To_v1_CustomResourceDefinition(in, out, s)
}

func autoConvert_v1_CustomResourceDefinitionList_To_core_CustomResourceDefinitionList(in *CustomResourceDefinitionList, out *core.CustomResourceDefinitionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]core.CustomResourceDefinition)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_CustomResourceDefinitionList_To_core_CustomResourceDefinitionList is an autogenerated conversion function.
func Convert_v1_CustomResourceDefinitionList_To_core_CustomResourceDefinitionList(in *CustomResourceDefinitionList, out *core.CustomResourceDefinitionList, s conversion.Scope) error {
	return autoConvert_v1_CustomResourceDefinitionList_To_core_CustomResourceDefinitionList(in, out, s)
}

func autoConvert_core_CustomResourceDefinitionList_To_v1_CustomResourceDefinitionList(in *core.CustomResourceDefinitionList, out *CustomResourceDefinitionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]CustomResourceDefinition)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_core_CustomResourceDefinitionList_To_v1_CustomResourceDefinitionList is an autogenerated conversion function.
func Convert_core_CustomResourceDefinitionList_To_v1_CustomResourceDefinitionList(in *core.CustomResourceDefinitionList, out *CustomResourceDefinitionList, s conversion.Scope) error {
	return autoConvert_core_CustomResourceDefinitionList_To_v1_CustomResourceDefinitionList(in, out, s)
}

func autoConvert_v1_CustomResourceDefinitionNames_To_core_CustomResourceDefinitionNames(in *CustomResourceDefinitionNames, out *core.CustomResourceDefinitionNames, s conversion.Scope) error {
	out.Plural = in.Plural
	out.Singular = in.Singular
	out.Kind = in.Kind
	return nil
}

// Convert_v1_CustomResourceDefinitionNames_To_core_CustomResourceDefinitionNames is an autogenerated conversion function.
func Convert_v1_CustomResourceDefinitionNames_To_core_CustomResourceDefinitionNames(in *CustomResourceDefinitionNames, out *core.CustomResourceDefinitionNames, s conversion.Scope) error {
	return autoConvert_v1_CustomResourceDefinitionNames_To_core_CustomResourceDefinitionNames(in, out, s)
}

func autoConvert_core_CustomResourceDefinitionNames_To_v1_CustomResourceDefinitionNames(in *core.CustomResourceDefinitionNames, out *CustomResourceDefinitionNames, s conversion.Scope) error {
	out.Plural = in.Plural
	out.Singular = in.Singular
	out.Kind = in.Kind
	return nil
}

// Convert_core_CustomResourceDefinitionNames_To_v1_CustomResourceDefinitionNames is an autogenerated conversion function.
func Convert_core_CustomResourceDefinitionNames_To_v1_CustomResourceDefinitionNames(in *core.CustomResourceDefinitionNames, out *CustomResourceDefinitionNames, s conversion.Scope) error {
	return autoConvert_core_CustomResourceDefinitionNames_To_v1_CustomResourceDefinitionNames(in, out, s)
}

func autoConvert_v1_CustomResourceDefinitionSpec_To_core_CustomResourceDefinitionSpec(in *CustomResourceDefinitionSpec, out *core.CustomResourceDefinitionSpec, s conversion.Scope) error {
	out.Group = in.Group
	if err := Convert_v1_CustomResourceDefinitionNames_To_core_CustomResourceDefinitionNames(&in.Names, &out.Names, s); err != nil {
		return err
	}
	out.Versions = *(*[]core.CustomResourceDefinitionVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_v1_CustomResourceDefinitionSpec_To_core_CustomResourceDefinitionSpec is an autogenerated conversion function.
func Convert_v1_CustomResourceDefinitionSpec_To_core_CustomResourceDefinitionSpec(in *CustomResourceDefinitionSpec, out *core.CustomResourceDefinitionSpec, s conversion.Scope) error {
	return autoConvert_v1_CustomResourceDefinitionSpec_To_core_CustomResourceDefinitionSpec(in, out, s)
}

func autoConvert_core_CustomResourceDefinitionSpec_To_v1_CustomResourceDefinitionSpec(in *core.CustomResourceDefinitionSpec, out *CustomResourceDefinitionSpec, s conversion.Scope) error {
	out.Group = in.Group
	if err := Convert_core_CustomResourceDefinitionNames_To_v1_CustomResourceDefinitionNames(&in.Names, &out.Names, s); err != nil {
		return err
	}
	out.Versions = *(*[]CustomResourceDefinitionVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_core_CustomResourceDefinitionSpec_To_v1_CustomResourceDefinitionSpec is an autogenerated conversion function.
func Convert_core_CustomResourceDefinitionSpec_To_v1_CustomResourceDefinitionSpec(in *core.CustomResourceDefinitionSpec, out *CustomResourceDefinitionSpec, s conversion.Scope) error {
	return autoConvert_core_CustomResourceDefinitionSpec_To_v1_CustomResourceDefinitionSpec(in, out, s)
}

func autoConvert_v1_CustomResourceDefinitionValidation_To_core_CustomResourceDefinitionValidation(in *CustomResourceDefinitionValidation, out *core.CustomResourceDefinitionValidation, s conversion.Scope) error {
	if err := Convert_v1_JSONSchemaProps_To_core_JSONSchemaProps(&in.OpenAPIV3Schema, &out.OpenAPIV3Schema, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_CustomResourceDefinitionValidation_To_core_CustomResourceDefinitionValidation is an autogenerated conversion function.
func Convert_v1_CustomResourceDefinitionValidation_To_core_CustomResourceDefinitionValidation(in *CustomResourceDefinitionValidation, out *core.CustomResourceDefinitionValidation, s conversion.Scope) error {
	return autoConvert_v1_CustomResourceDefinitionValidation_To_core_CustomResourceDefinitionValidation(in, out, s)
}

func autoConvert_core_CustomResourceDefinitionValidation_To_v1_CustomResourceDefinitionValidation(in *core.CustomResourceDefinitionValidation, out *CustomResourceDefinitionValidation, s conversion.Scope) error {
	if err := Convert_core_JSONSchemaProps_To_v1_JSONSchemaProps(&in.OpenAPIV3Schema, &out.OpenAPIV3Schema, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_CustomResourceDefinitionValidation_To_v1_CustomResourceDefinitionValidation is an autogenerated conversion function.
func Convert_core_CustomResourceDefinitionValidation_To_v1_CustomResourceDefinitionValidation(in *core.CustomResourceDefinitionValidation, out *CustomResourceDefinitionValidation, s conversion.Scope) error {
	return autoConvert_core_CustomResourceDefinitionValidation_To_v1_CustomResourceDefinitionValidation(in, out, s)
}

func autoConvert_v1_CustomResourceDefinitionVersion_To_core_CustomResourceDefinitionVersion(in *CustomResourceDefinitionVersion, out *core.CustomResourceDefinitionVersion, s conversion.Scope) error {
	out.Name = in.Name
	out.Served = in.Served
	out.Storage = in.Storage
	if err := Convert_v1_CustomResourceDefinitionValidation_To_core_CustomResourceDefinitionValidation(&in.Schema, &out.Schema, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_CustomResourceDefinitionVersion_To_core_CustomResourceDefinitionVersion is an autogenerated conversion function.
func Convert_v1_CustomResourceDefinitionVersion_To_core_CustomResourceDefinitionVersion(in *CustomResourceDefinitionVersion, out *core.CustomResourceDefinitionVersion, s conversion.Scope) error {
	return autoConvert_v1_CustomResourceDefinitionVersion_To_core_CustomResourceDefinitionVersion(in, out, s)
}

func autoConvert_core_CustomResourceDefinitionVersion_To_v1_CustomResourceDefinitionVersion(in *core.CustomResourceDefinitionVersion, out *CustomResourceDefinitionVersion, s conversion.Scope) error {
	out.Name = in.Name
	out.Served = in.Served
	out.Storage = in.Storage
	if err := Convert_core_CustomResourceDefinitionValidation_To_v1_CustomResourceDefinitionValidation(&in.Schema, &out.Schema, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_CustomResourceDefinitionVersion_To_v1_CustomResourceDefinitionVersion is an autogenerated conversion function.
func Convert_core_CustomResourceDefinitionVersion_To_v1_CustomResourceDefinitionVersion(in *core.CustomResourceDefinitionVersion, out *CustomResourceDefinitionVersion, s conversion.Scope) error {
	return autoConvert_core_CustomResourceDefinitionVersion_To_v1_CustomResourceDefinitionVersion(in, out, s)
}

func autoConvert_v1_ExternalDocumentation_To_core_ExternalDocumentation(in *ExternalDocumentation, out *core.ExternalDocumentation, s conversion.Scope) error {
	out.Description = in.Description
	out.URL = in.URL
	return nil
}

// Convert_v1_ExternalDocumentation_To_core_ExternalDocumentation is an autogenerated conversion function.
func Convert_v1_ExternalDocumentation_To_core_ExternalDocumentation(in *ExternalDocumentation, out *core.ExternalDocumentation, s conversion.Scope) error {
	return autoConvert_v1_ExternalDocumentation_To_core_ExternalDocumentation(in, out, s)
}

func autoConvert_core_ExternalDocumentation_To_v1_ExternalDocumentation(in *core.ExternalDocumentation, out *ExternalDocumentation, s conversion.Scope) error {
	out.Description = in.Description
	out.URL = in.URL
	return nil
}

// Convert_core_ExternalDocumentation_To_v1_ExternalDocumentation is an autogenerated conversion function.
func Convert_core_ExternalDocumentation_To_v1_ExternalDocumentation(in *core.ExternalDocumentation, out *ExternalDocumentation, s conversion.Scope) error {
	return autoConvert_core_ExternalDocumentation_To_v1_ExternalDocumentation(in, out, s)
}

func autoConvert_v1_FormDefinition_To_core_FormDefinition(in *FormDefinition, out *core.FormDefinition, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_FormDefinitionSpec_To_core_FormDefinitionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_FormDefinition_To_core_FormDefinition is an autogenerated conversion function.
func Convert_v1_FormDefinition_To_core_FormDefinition(in *FormDefinition, out *core.FormDefinition, s conversion.Scope) error {
	return autoConvert_v1_FormDefinition_To_core_FormDefinition(in, out, s)
}

func autoConvert_core_FormDefinition_To_v1_FormDefinition(in *core.FormDefinition, out *FormDefinition, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_core_FormDefinitionSpec_To_v1_FormDefinitionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_FormDefinition_To_v1_FormDefinition is an autogenerated conversion function.
func Convert_core_FormDefinition_To_v1_FormDefinition(in *core.FormDefinition, out *FormDefinition, s conversion.Scope) error {
	return autoConvert_core_FormDefinition_To_v1_FormDefinition(in, out, s)
}

func autoConvert_v1_FormDefinitionList_To_core_FormDefinitionList(in *FormDefinitionList, out *core.FormDefinitionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]core.FormDefinition)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_FormDefinitionList_To_core_FormDefinitionList is an autogenerated conversion function.
func Convert_v1_FormDefinitionList_To_core_FormDefinitionList(in *FormDefinitionList, out *core.FormDefinitionList, s conversion.Scope) error {
	return autoConvert_v1_FormDefinitionList_To_core_FormDefinitionList(in, out, s)
}

func autoConvert_core_FormDefinitionList_To_v1_FormDefinitionList(in *core.FormDefinitionList, out *FormDefinitionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]FormDefinition)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_core_FormDefinitionList_To_v1_FormDefinitionList is an autogenerated conversion function.
func Convert_core_FormDefinitionList_To_v1_FormDefinitionList(in *core.FormDefinitionList, out *FormDefinitionList, s conversion.Scope) error {
	return autoConvert_core_FormDefinitionList_To_v1_FormDefinitionList(in, out, s)
}

func autoConvert_v1_FormDefinitionNames_To_core_FormDefinitionNames(in *FormDefinitionNames, out *core.FormDefinitionNames, s conversion.Scope) error {
	out.Plural = in.Plural
	out.Singular = in.Singular
	out.Kind = in.Kind
	return nil
}

// Convert_v1_FormDefinitionNames_To_core_FormDefinitionNames is an autogenerated conversion function.
func Convert_v1_FormDefinitionNames_To_core_FormDefinitionNames(in *FormDefinitionNames, out *core.FormDefinitionNames, s conversion.Scope) error {
	return autoConvert_v1_FormDefinitionNames_To_core_FormDefinitionNames(in, out, s)
}

func autoConvert_core_FormDefinitionNames_To_v1_FormDefinitionNames(in *core.FormDefinitionNames, out *FormDefinitionNames, s conversion.Scope) error {
	out.Plural = in.Plural
	out.Singular = in.Singular
	out.Kind = in.Kind
	return nil
}

// Convert_core_FormDefinitionNames_To_v1_FormDefinitionNames is an autogenerated conversion function.
func Convert_core_FormDefinitionNames_To_v1_FormDefinitionNames(in *core.FormDefinitionNames, out *FormDefinitionNames, s conversion.Scope) error {
	return autoConvert_core_FormDefinitionNames_To_v1_FormDefinitionNames(in, out, s)
}

func autoConvert_v1_FormDefinitionSchema_To_core_FormDefinitionSchema(in *FormDefinitionSchema, out *core.FormDefinitionSchema, s conversion.Scope) error {
	if err := Convert_v1_FormElementDefinition_To_core_FormElementDefinition(&in.Root, &out.Root, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_FormDefinitionSchema_To_core_FormDefinitionSchema is an autogenerated conversion function.
func Convert_v1_FormDefinitionSchema_To_core_FormDefinitionSchema(in *FormDefinitionSchema, out *core.FormDefinitionSchema, s conversion.Scope) error {
	return autoConvert_v1_FormDefinitionSchema_To_core_FormDefinitionSchema(in, out, s)
}

func autoConvert_core_FormDefinitionSchema_To_v1_FormDefinitionSchema(in *core.FormDefinitionSchema, out *FormDefinitionSchema, s conversion.Scope) error {
	if err := Convert_core_FormElementDefinition_To_v1_FormElementDefinition(&in.Root, &out.Root, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_FormDefinitionSchema_To_v1_FormDefinitionSchema is an autogenerated conversion function.
func Convert_core_FormDefinitionSchema_To_v1_FormDefinitionSchema(in *core.FormDefinitionSchema, out *FormDefinitionSchema, s conversion.Scope) error {
	return autoConvert_core_FormDefinitionSchema_To_v1_FormDefinitionSchema(in, out, s)
}

func autoConvert_v1_FormDefinitionSpec_To_core_FormDefinitionSpec(in *FormDefinitionSpec, out *core.FormDefinitionSpec, s conversion.Scope) error {
	out.Group = in.Group
	if err := Convert_v1_FormDefinitionNames_To_core_FormDefinitionNames(&in.Names, &out.Names, s); err != nil {
		return err
	}
	out.Versions = *(*[]core.FormDefinitionVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_v1_FormDefinitionSpec_To_core_FormDefinitionSpec is an autogenerated conversion function.
func Convert_v1_FormDefinitionSpec_To_core_FormDefinitionSpec(in *FormDefinitionSpec, out *core.FormDefinitionSpec, s conversion.Scope) error {
	return autoConvert_v1_FormDefinitionSpec_To_core_FormDefinitionSpec(in, out, s)
}

func autoConvert_core_FormDefinitionSpec_To_v1_FormDefinitionSpec(in *core.FormDefinitionSpec, out *FormDefinitionSpec, s conversion.Scope) error {
	out.Group = in.Group
	if err := Convert_core_FormDefinitionNames_To_v1_FormDefinitionNames(&in.Names, &out.Names, s); err != nil {
		return err
	}
	out.Versions = *(*[]FormDefinitionVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_core_FormDefinitionSpec_To_v1_FormDefinitionSpec is an autogenerated conversion function.
func Convert_core_FormDefinitionSpec_To_v1_FormDefinitionSpec(in *core.FormDefinitionSpec, out *FormDefinitionSpec, s conversion.Scope) error {
	return autoConvert_core_FormDefinitionSpec_To_v1_FormDefinitionSpec(in, out, s)
}

func autoConvert_v1_FormDefinitionValidation_To_core_FormDefinitionValidation(in *FormDefinitionValidation, out *core.FormDefinitionValidation, s conversion.Scope) error {
	if err := Convert_v1_FormDefinitionSchema_To_core_FormDefinitionSchema(&in.FormSchema, &out.FormSchema, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_FormDefinitionValidation_To_core_FormDefinitionValidation is an autogenerated conversion function.
func Convert_v1_FormDefinitionValidation_To_core_FormDefinitionValidation(in *FormDefinitionValidation, out *core.FormDefinitionValidation, s conversion.Scope) error {
	return autoConvert_v1_FormDefinitionValidation_To_core_FormDefinitionValidation(in, out, s)
}

func autoConvert_core_FormDefinitionValidation_To_v1_FormDefinitionValidation(in *core.FormDefinitionValidation, out *FormDefinitionValidation, s conversion.Scope) error {
	if err := Convert_core_FormDefinitionSchema_To_v1_FormDefinitionSchema(&in.FormSchema, &out.FormSchema, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_FormDefinitionValidation_To_v1_FormDefinitionValidation is an autogenerated conversion function.
func Convert_core_FormDefinitionValidation_To_v1_FormDefinitionValidation(in *core.FormDefinitionValidation, out *FormDefinitionValidation, s conversion.Scope) error {
	return autoConvert_core_FormDefinitionValidation_To_v1_FormDefinitionValidation(in, out, s)
}

func autoConvert_v1_FormDefinitionVersion_To_core_FormDefinitionVersion(in *FormDefinitionVersion, out *core.FormDefinitionVersion, s conversion.Scope) error {
	out.Name = in.Name
	out.Served = in.Served
	out.Storage = in.Storage
	if err := Convert_v1_FormDefinitionValidation_To_core_FormDefinitionValidation(&in.Schema, &out.Schema, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_FormDefinitionVersion_To_core_FormDefinitionVersion is an autogenerated conversion function.
func Convert_v1_FormDefinitionVersion_To_core_FormDefinitionVersion(in *FormDefinitionVersion, out *core.FormDefinitionVersion, s conversion.Scope) error {
	return autoConvert_v1_FormDefinitionVersion_To_core_FormDefinitionVersion(in, out, s)
}

func autoConvert_core_FormDefinitionVersion_To_v1_FormDefinitionVersion(in *core.FormDefinitionVersion, out *FormDefinitionVersion, s conversion.Scope) error {
	out.Name = in.Name
	out.Served = in.Served
	out.Storage = in.Storage
	if err := Convert_core_FormDefinitionValidation_To_v1_FormDefinitionValidation(&in.Schema, &out.Schema, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_FormDefinitionVersion_To_v1_FormDefinitionVersion is an autogenerated conversion function.
func Convert_core_FormDefinitionVersion_To_v1_FormDefinitionVersion(in *core.FormDefinitionVersion, out *FormDefinitionVersion, s conversion.Scope) error {
	return autoConvert_core_FormDefinitionVersion_To_v1_FormDefinitionVersion(in, out, s)
}

func autoConvert_v1_FormElementDefinition_To_core_FormElementDefinition(in *FormElementDefinition, out *core.FormElementDefinition, s conversion.Scope) error {
	out.Key = in.Key
	out.Label = *(*core.TranslatedStrings)(unsafe.Pointer(&in.Label))
	out.Description = *(*core.TranslatedStrings)(unsafe.Pointer(&in.Description))
	out.Help = *(*core.TranslatedStrings)(unsafe.Pointer(&in.Help))
	out.Type = core.FormElementType(in.Type)
	out.Required = in.Required
	out.Children = *(*[]core.FormElementDefinition)(unsafe.Pointer(&in.Children))
	out.Min = in.Min
	out.Max = in.Max
	out.Pattern = in.Pattern
	out.MinLength = in.MinLength
	out.MaxLength = (*int64)(unsafe.Pointer(in.MaxLength))
	return nil
}

// Convert_v1_FormElementDefinition_To_core_FormElementDefinition is an autogenerated conversion function.
func Convert_v1_FormElementDefinition_To_core_FormElementDefinition(in *FormElementDefinition, out *core.FormElementDefinition, s conversion.Scope) error {
	return autoConvert_v1_FormElementDefinition_To_core_FormElementDefinition(in, out, s)
}

func autoConvert_core_FormElementDefinition_To_v1_FormElementDefinition(in *core.FormElementDefinition, out *FormElementDefinition, s conversion.Scope) error {
	out.Key = in.Key
	out.Label = *(*TranslatedStrings)(unsafe.Pointer(&in.Label))
	out.Description = *(*TranslatedStrings)(unsafe.Pointer(&in.Description))
	out.Help = *(*TranslatedStrings)(unsafe.Pointer(&in.Help))
	out.Type = FormElementType(in.Type)
	out.Required = in.Required
	out.Children = *(*[]FormElementDefinition)(unsafe.Pointer(&in.Children))
	out.Min = in.Min
	out.Max = in.Max
	out.Pattern = in.Pattern
	out.MinLength = in.MinLength
	out.MaxLength = (*int64)(unsafe.Pointer(in.MaxLength))
	return nil
}

// Convert_core_FormElementDefinition_To_v1_FormElementDefinition is an autogenerated conversion function.
func Convert_core_FormElementDefinition_To_v1_FormElementDefinition(in *core.FormElementDefinition, out *FormElementDefinition, s conversion.Scope) error {
	return autoConvert_core_FormElementDefinition_To_v1_FormElementDefinition(in, out, s)
}

func autoConvert_v1_JSON_To_core_JSON(in *JSON, out *core.JSON, s conversion.Scope) error {
	out.Raw = *(*[]byte)(unsafe.Pointer(&in.Raw))
	return nil
}

// Convert_v1_JSON_To_core_JSON is an autogenerated conversion function.
func Convert_v1_JSON_To_core_JSON(in *JSON, out *core.JSON, s conversion.Scope) error {
	return autoConvert_v1_JSON_To_core_JSON(in, out, s)
}

func autoConvert_core_JSON_To_v1_JSON(in *core.JSON, out *JSON, s conversion.Scope) error {
	out.Raw = *(*[]byte)(unsafe.Pointer(&in.Raw))
	return nil
}

// Convert_core_JSON_To_v1_JSON is an autogenerated conversion function.
func Convert_core_JSON_To_v1_JSON(in *core.JSON, out *JSON, s conversion.Scope) error {
	return autoConvert_core_JSON_To_v1_JSON(in, out, s)
}

func autoConvert_v1_JSONSchemaProps_To_core_JSONSchemaProps(in *JSONSchemaProps, out *core.JSONSchemaProps, s conversion.Scope) error {
	out.ID = in.ID
	out.Schema = core.JSONSchemaURL(in.Schema)
	out.Ref = (*string)(unsafe.Pointer(in.Ref))
	out.Description = in.Description
	out.Type = in.Type
	out.Format = in.Format
	out.Title = in.Title
	out.Default = (*core.JSON)(unsafe.Pointer(in.Default))
	out.Maximum = (*float64)(unsafe.Pointer(in.Maximum))
	out.ExclusiveMaximum = in.ExclusiveMaximum
	out.Minimum = (*float64)(unsafe.Pointer(in.Minimum))
	out.ExclusiveMinimum = in.ExclusiveMinimum
	out.MaxLength = (*int64)(unsafe.Pointer(in.MaxLength))
	out.MinLength = (*int64)(unsafe.Pointer(in.MinLength))
	out.Pattern = in.Pattern
	out.MaxItems = (*int64)(unsafe.Pointer(in.MaxItems))
	out.MinItems = (*int64)(unsafe.Pointer(in.MinItems))
	out.UniqueItems = in.UniqueItems
	out.MultipleOf = (*float64)(unsafe.Pointer(in.MultipleOf))
	out.Enum = *(*[]core.JSON)(unsafe.Pointer(&in.Enum))
	out.MaxProperties = (*int64)(unsafe.Pointer(in.MaxProperties))
	out.MinProperties = (*int64)(unsafe.Pointer(in.MinProperties))
	out.Required = *(*[]string)(unsafe.Pointer(&in.Required))
	out.Items = (*core.JSONSchemaPropsOrArray)(unsafe.Pointer(in.Items))
	out.AllOf = *(*[]core.JSONSchemaProps)(unsafe.Pointer(&in.AllOf))
	out.OneOf = *(*[]core.JSONSchemaProps)(unsafe.Pointer(&in.OneOf))
	out.AnyOf = *(*[]core.JSONSchemaProps)(unsafe.Pointer(&in.AnyOf))
	out.Not = (*core.JSONSchemaProps)(unsafe.Pointer(in.Not))
	out.Properties = *(*map[string]core.JSONSchemaProps)(unsafe.Pointer(&in.Properties))
	out.AdditionalProperties = (*core.JSONSchemaPropsOrBool)(unsafe.Pointer(in.AdditionalProperties))
	out.PatternProperties = *(*map[string]core.JSONSchemaProps)(unsafe.Pointer(&in.PatternProperties))
	out.Dependencies = *(*core.JSONSchemaDependencies)(unsafe.Pointer(&in.Dependencies))
	out.AdditionalItems = (*core.JSONSchemaPropsOrBool)(unsafe.Pointer(in.AdditionalItems))
	out.Definitions = *(*core.JSONSchemaDefinitions)(unsafe.Pointer(&in.Definitions))
	out.ExternalDocs = (*core.ExternalDocumentation)(unsafe.Pointer(in.ExternalDocs))
	out.Example = (*core.JSON)(unsafe.Pointer(in.Example))
	out.Nullable = in.Nullable
	out.XPreserveUnknownFields = (*bool)(unsafe.Pointer(in.XPreserveUnknownFields))
	out.XEmbeddedResource = in.XEmbeddedResource
	out.XIntOrString = in.XIntOrString
	out.XListMapKeys = *(*[]string)(unsafe.Pointer(&in.XListMapKeys))
	out.XListType = (*string)(unsafe.Pointer(in.XListType))
	out.XMapType = (*string)(unsafe.Pointer(in.XMapType))
	return nil
}

// Convert_v1_JSONSchemaProps_To_core_JSONSchemaProps is an autogenerated conversion function.
func Convert_v1_JSONSchemaProps_To_core_JSONSchemaProps(in *JSONSchemaProps, out *core.JSONSchemaProps, s conversion.Scope) error {
	return autoConvert_v1_JSONSchemaProps_To_core_JSONSchemaProps(in, out, s)
}

func autoConvert_core_JSONSchemaProps_To_v1_JSONSchemaProps(in *core.JSONSchemaProps, out *JSONSchemaProps, s conversion.Scope) error {
	out.ID = in.ID
	out.Schema = JSONSchemaURL(in.Schema)
	out.Ref = (*string)(unsafe.Pointer(in.Ref))
	out.Description = in.Description
	out.Type = in.Type
	out.Format = in.Format
	out.Title = in.Title
	out.Default = (*JSON)(unsafe.Pointer(in.Default))
	out.Maximum = (*float64)(unsafe.Pointer(in.Maximum))
	out.ExclusiveMaximum = in.ExclusiveMaximum
	out.Minimum = (*float64)(unsafe.Pointer(in.Minimum))
	out.ExclusiveMinimum = in.ExclusiveMinimum
	out.MaxLength = (*int64)(unsafe.Pointer(in.MaxLength))
	out.MinLength = (*int64)(unsafe.Pointer(in.MinLength))
	out.Pattern = in.Pattern
	out.MaxItems = (*int64)(unsafe.Pointer(in.MaxItems))
	out.MinItems = (*int64)(unsafe.Pointer(in.MinItems))
	out.UniqueItems = in.UniqueItems
	out.MultipleOf = (*float64)(unsafe.Pointer(in.MultipleOf))
	out.Enum = *(*[]JSON)(unsafe.Pointer(&in.Enum))
	out.MaxProperties = (*int64)(unsafe.Pointer(in.MaxProperties))
	out.MinProperties = (*int64)(unsafe.Pointer(in.MinProperties))
	out.Required = *(*[]string)(unsafe.Pointer(&in.Required))
	out.Items = (*JSONSchemaPropsOrArray)(unsafe.Pointer(in.Items))
	out.AllOf = *(*[]JSONSchemaProps)(unsafe.Pointer(&in.AllOf))
	out.OneOf = *(*[]JSONSchemaProps)(unsafe.Pointer(&in.OneOf))
	out.AnyOf = *(*[]JSONSchemaProps)(unsafe.Pointer(&in.AnyOf))
	out.Not = (*JSONSchemaProps)(unsafe.Pointer(in.Not))
	out.Properties = *(*map[string]JSONSchemaProps)(unsafe.Pointer(&in.Properties))
	out.AdditionalProperties = (*JSONSchemaPropsOrBool)(unsafe.Pointer(in.AdditionalProperties))
	out.PatternProperties = *(*map[string]JSONSchemaProps)(unsafe.Pointer(&in.PatternProperties))
	out.Dependencies = *(*JSONSchemaDependencies)(unsafe.Pointer(&in.Dependencies))
	out.AdditionalItems = (*JSONSchemaPropsOrBool)(unsafe.Pointer(in.AdditionalItems))
	out.Definitions = *(*JSONSchemaDefinitions)(unsafe.Pointer(&in.Definitions))
	out.ExternalDocs = (*ExternalDocumentation)(unsafe.Pointer(in.ExternalDocs))
	out.Example = (*JSON)(unsafe.Pointer(in.Example))
	out.Nullable = in.Nullable
	out.XPreserveUnknownFields = (*bool)(unsafe.Pointer(in.XPreserveUnknownFields))
	out.XEmbeddedResource = in.XEmbeddedResource
	out.XIntOrString = in.XIntOrString
	out.XListMapKeys = *(*[]string)(unsafe.Pointer(&in.XListMapKeys))
	out.XListType = (*string)(unsafe.Pointer(in.XListType))
	out.XMapType = (*string)(unsafe.Pointer(in.XMapType))
	return nil
}

// Convert_core_JSONSchemaProps_To_v1_JSONSchemaProps is an autogenerated conversion function.
func Convert_core_JSONSchemaProps_To_v1_JSONSchemaProps(in *core.JSONSchemaProps, out *JSONSchemaProps, s conversion.Scope) error {
	return autoConvert_core_JSONSchemaProps_To_v1_JSONSchemaProps(in, out, s)
}

func autoConvert_v1_JSONSchemaPropsOrArray_To_core_JSONSchemaPropsOrArray(in *JSONSchemaPropsOrArray, out *core.JSONSchemaPropsOrArray, s conversion.Scope) error {
	out.Schema = (*core.JSONSchemaProps)(unsafe.Pointer(in.Schema))
	out.JSONSchemas = *(*[]core.JSONSchemaProps)(unsafe.Pointer(&in.JSONSchemas))
	return nil
}

// Convert_v1_JSONSchemaPropsOrArray_To_core_JSONSchemaPropsOrArray is an autogenerated conversion function.
func Convert_v1_JSONSchemaPropsOrArray_To_core_JSONSchemaPropsOrArray(in *JSONSchemaPropsOrArray, out *core.JSONSchemaPropsOrArray, s conversion.Scope) error {
	return autoConvert_v1_JSONSchemaPropsOrArray_To_core_JSONSchemaPropsOrArray(in, out, s)
}

func autoConvert_core_JSONSchemaPropsOrArray_To_v1_JSONSchemaPropsOrArray(in *core.JSONSchemaPropsOrArray, out *JSONSchemaPropsOrArray, s conversion.Scope) error {
	out.Schema = (*JSONSchemaProps)(unsafe.Pointer(in.Schema))
	out.JSONSchemas = *(*[]JSONSchemaProps)(unsafe.Pointer(&in.JSONSchemas))
	return nil
}

// Convert_core_JSONSchemaPropsOrArray_To_v1_JSONSchemaPropsOrArray is an autogenerated conversion function.
func Convert_core_JSONSchemaPropsOrArray_To_v1_JSONSchemaPropsOrArray(in *core.JSONSchemaPropsOrArray, out *JSONSchemaPropsOrArray, s conversion.Scope) error {
	return autoConvert_core_JSONSchemaPropsOrArray_To_v1_JSONSchemaPropsOrArray(in, out, s)
}

func autoConvert_v1_JSONSchemaPropsOrBool_To_core_JSONSchemaPropsOrBool(in *JSONSchemaPropsOrBool, out *core.JSONSchemaPropsOrBool, s conversion.Scope) error {
	out.Allows = in.Allows
	out.Schema = (*core.JSONSchemaProps)(unsafe.Pointer(in.Schema))
	return nil
}

// Convert_v1_JSONSchemaPropsOrBool_To_core_JSONSchemaPropsOrBool is an autogenerated conversion function.
func Convert_v1_JSONSchemaPropsOrBool_To_core_JSONSchemaPropsOrBool(in *JSONSchemaPropsOrBool, out *core.JSONSchemaPropsOrBool, s conversion.Scope) error {
	return autoConvert_v1_JSONSchemaPropsOrBool_To_core_JSONSchemaPropsOrBool(in, out, s)
}

func autoConvert_core_JSONSchemaPropsOrBool_To_v1_JSONSchemaPropsOrBool(in *core.JSONSchemaPropsOrBool, out *JSONSchemaPropsOrBool, s conversion.Scope) error {
	out.Allows = in.Allows
	out.Schema = (*JSONSchemaProps)(unsafe.Pointer(in.Schema))
	return nil
}

// Convert_core_JSONSchemaPropsOrBool_To_v1_JSONSchemaPropsOrBool is an autogenerated conversion function.
func Convert_core_JSONSchemaPropsOrBool_To_v1_JSONSchemaPropsOrBool(in *core.JSONSchemaPropsOrBool, out *JSONSchemaPropsOrBool, s conversion.Scope) error {
	return autoConvert_core_JSONSchemaPropsOrBool_To_v1_JSONSchemaPropsOrBool(in, out, s)
}

func autoConvert_v1_JSONSchemaPropsOrStringArray_To_core_JSONSchemaPropsOrStringArray(in *JSONSchemaPropsOrStringArray, out *core.JSONSchemaPropsOrStringArray, s conversion.Scope) error {
	out.Schema = (*core.JSONSchemaProps)(unsafe.Pointer(in.Schema))
	out.Property = *(*[]string)(unsafe.Pointer(&in.Property))
	return nil
}

// Convert_v1_JSONSchemaPropsOrStringArray_To_core_JSONSchemaPropsOrStringArray is an autogenerated conversion function.
func Convert_v1_JSONSchemaPropsOrStringArray_To_core_JSONSchemaPropsOrStringArray(in *JSONSchemaPropsOrStringArray, out *core.JSONSchemaPropsOrStringArray, s conversion.Scope) error {
	return autoConvert_v1_JSONSchemaPropsOrStringArray_To_core_JSONSchemaPropsOrStringArray(in, out, s)
}

func autoConvert_core_JSONSchemaPropsOrStringArray_To_v1_JSONSchemaPropsOrStringArray(in *core.JSONSchemaPropsOrStringArray, out *JSONSchemaPropsOrStringArray, s conversion.Scope) error {
	out.Schema = (*JSONSchemaProps)(unsafe.Pointer(in.Schema))
	out.Property = *(*[]string)(unsafe.Pointer(&in.Property))
	return nil
}

// Convert_core_JSONSchemaPropsOrStringArray_To_v1_JSONSchemaPropsOrStringArray is an autogenerated conversion function.
func Convert_core_JSONSchemaPropsOrStringArray_To_v1_JSONSchemaPropsOrStringArray(in *core.JSONSchemaPropsOrStringArray, out *JSONSchemaPropsOrStringArray, s conversion.Scope) error {
	return autoConvert_core_JSONSchemaPropsOrStringArray_To_v1_JSONSchemaPropsOrStringArray(in, out, s)
}

func autoConvert_v1_OperatingScope_To_core_OperatingScope(in *OperatingScope, out *core.OperatingScope, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_OperatingScopeSpec_To_core_OperatingScopeSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_OperatingScope_To_core_OperatingScope is an autogenerated conversion function.
func Convert_v1_OperatingScope_To_core_OperatingScope(in *OperatingScope, out *core.OperatingScope, s conversion.Scope) error {
	return autoConvert_v1_OperatingScope_To_core_OperatingScope(in, out, s)
}

func autoConvert_core_OperatingScope_To_v1_OperatingScope(in *core.OperatingScope, out *OperatingScope, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_core_OperatingScopeSpec_To_v1_OperatingScopeSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_OperatingScope_To_v1_OperatingScope is an autogenerated conversion function.
func Convert_core_OperatingScope_To_v1_OperatingScope(in *core.OperatingScope, out *OperatingScope, s conversion.Scope) error {
	return autoConvert_core_OperatingScope_To_v1_OperatingScope(in, out, s)
}

func autoConvert_v1_OperatingScopeList_To_core_OperatingScopeList(in *OperatingScopeList, out *core.OperatingScopeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]core.OperatingScope)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_OperatingScopeList_To_core_OperatingScopeList is an autogenerated conversion function.
func Convert_v1_OperatingScopeList_To_core_OperatingScopeList(in *OperatingScopeList, out *core.OperatingScopeList, s conversion.Scope) error {
	return autoConvert_v1_OperatingScopeList_To_core_OperatingScopeList(in, out, s)
}

func autoConvert_core_OperatingScopeList_To_v1_OperatingScopeList(in *core.OperatingScopeList, out *OperatingScopeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]OperatingScope)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_core_OperatingScopeList_To_v1_OperatingScopeList is an autogenerated conversion function.
func Convert_core_OperatingScopeList_To_v1_OperatingScopeList(in *core.OperatingScopeList, out *OperatingScopeList, s conversion.Scope) error {
	return autoConvert_core_OperatingScopeList_To_v1_OperatingScopeList(in, out, s)
}

func autoConvert_v1_OperatingScopeSpec_To_core_OperatingScopeSpec(in *OperatingScopeSpec, out *core.OperatingScopeSpec, s conversion.Scope) error {
	out.AdditionalBeneficiaryInformation = *(*[]core.AdditionalBeneficiaryInformation)(unsafe.Pointer(&in.AdditionalBeneficiaryInformation))
	return nil
}

// Convert_v1_OperatingScopeSpec_To_core_OperatingScopeSpec is an autogenerated conversion function.
func Convert_v1_OperatingScopeSpec_To_core_OperatingScopeSpec(in *OperatingScopeSpec, out *core.OperatingScopeSpec, s conversion.Scope) error {
	return autoConvert_v1_OperatingScopeSpec_To_core_OperatingScopeSpec(in, out, s)
}

func autoConvert_core_OperatingScopeSpec_To_v1_OperatingScopeSpec(in *core.OperatingScopeSpec, out *OperatingScopeSpec, s conversion.Scope) error {
	out.AdditionalBeneficiaryInformation = *(*[]AdditionalBeneficiaryInformation)(unsafe.Pointer(&in.AdditionalBeneficiaryInformation))
	return nil
}

// Convert_core_OperatingScopeSpec_To_v1_OperatingScopeSpec is an autogenerated conversion function.
func Convert_core_OperatingScopeSpec_To_v1_OperatingScopeSpec(in *core.OperatingScopeSpec, out *OperatingScopeSpec, s conversion.Scope) error {
	return autoConvert_core_OperatingScopeSpec_To_v1_OperatingScopeSpec(in, out, s)
}

func autoConvert_v1_TranslatedString_To_core_TranslatedString(in *TranslatedString, out *core.TranslatedString, s conversion.Scope) error {
	out.Locale = in.Locale
	out.Value = in.Value
	return nil
}

// Convert_v1_TranslatedString_To_core_TranslatedString is an autogenerated conversion function.
func Convert_v1_TranslatedString_To_core_TranslatedString(in *TranslatedString, out *core.TranslatedString, s conversion.Scope) error {
	return autoConvert_v1_TranslatedString_To_core_TranslatedString(in, out, s)
}

func autoConvert_core_TranslatedString_To_v1_TranslatedString(in *core.TranslatedString, out *TranslatedString, s conversion.Scope) error {
	out.Locale = in.Locale
	out.Value = in.Value
	return nil
}

// Convert_core_TranslatedString_To_v1_TranslatedString is an autogenerated conversion function.
func Convert_core_TranslatedString_To_v1_TranslatedString(in *core.TranslatedString, out *TranslatedString, s conversion.Scope) error {
	return autoConvert_core_TranslatedString_To_v1_TranslatedString(in, out, s)
}

func autoConvert_v1_User_To_core_User(in *User, out *core.User, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Attributes = *(*map[string][]string)(unsafe.Pointer(&in.Attributes))
	return nil
}

// Convert_v1_User_To_core_User is an autogenerated conversion function.
func Convert_v1_User_To_core_User(in *User, out *core.User, s conversion.Scope) error {
	return autoConvert_v1_User_To_core_User(in, out, s)
}

func autoConvert_core_User_To_v1_User(in *core.User, out *User, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Attributes = *(*map[string][]string)(unsafe.Pointer(&in.Attributes))
	return nil
}

// Convert_core_User_To_v1_User is an autogenerated conversion function.
func Convert_core_User_To_v1_User(in *core.User, out *User, s conversion.Scope) error {
	return autoConvert_core_User_To_v1_User(in, out, s)
}

func autoConvert_v1_UserList_To_core_UserList(in *UserList, out *core.UserList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]core.User)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_UserList_To_core_UserList is an autogenerated conversion function.
func Convert_v1_UserList_To_core_UserList(in *UserList, out *core.UserList, s conversion.Scope) error {
	return autoConvert_v1_UserList_To_core_UserList(in, out, s)
}

func autoConvert_core_UserList_To_v1_UserList(in *core.UserList, out *UserList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]User)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_core_UserList_To_v1_UserList is an autogenerated conversion function.
func Convert_core_UserList_To_v1_UserList(in *core.UserList, out *UserList, s conversion.Scope) error {
	return autoConvert_core_UserList_To_v1_UserList(in, out, s)
}
