services:

  mongo1:
    image: mongo
    hostname: mongo1
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: on-failure
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rsmongo" ]
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'rsmongo',members:[{'_id':0,'host':'mongo1:27017','priority':4},{'_id':1,'host':'mongo2:27017','priority':2},{'_id':2,'host':'mongo3:27017','priority':1}]}).ok || rs.status().ok" | mongo --port 27017 --quiet) -eq 1
      interval: 10s
      start_period: 10s

  mongo2:
    image: mongo
    hostname: mongo2
    expose:
      - 27017
    ports:
      - 27018:27017
    restart: on-failure
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rsmongo" ]

  mongo3:
    image: mongo
    hostname: mongo3
    expose:
      - 27017
    ports:
      - 27019:27017
    restart: on-failure
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rsmongo" ]

  mongo-express:
    image: mongo-express
    container_name: "core-mongo-express"
    restart: on-failure
    links:
      - "mongo1"
      - "mongo2"
      - "mongo3"
    depends_on:
      - "mongo1"
      - "mongo2"
      - "mongo3"
    ports:
      - "8090:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo1,mongo2,mongo3

  redis:
    image: 'bitnami/redis:latest'
    container_name: "core-redis"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    restart: on-failure

  hydra_migrate:
    image: oryd/hydra:v1.10.2
    container_name: "core-hydra-migrate"
    command:
      - migrate
      - sql
      - --yes
      - postgres://hydra:secret@hydra_db:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    restart: on-failure

  hydra:
    image: oryd/hydra:v1.10.2
    container_name: "core-hydra"
    ports:
      - "4444:4444"
      - "4445:4445"
    command:
      - serve
      - all
      - --dangerous-force-http
    environment:
      - DSN=postgres://hydra:secret@hydra_db:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - SECRETS_SYSTEM=fVuJ0N1nFuymQjcnC4OWcIyo15gb0MYe
      - URLS_SELF_ISSUER=http://localhost:4444
      - URLS_CONSENT=http://localhost:9000/auth/consent
      - URLS_LOGIN=http://localhost:9000/auth/login
      - URLS_LOGOUT=http://localhost:9000/auth/logout
      - LOG_LEAK_SENSITIVE_VALUES=true
    restart: on-failure

  hydra_db:
    image: postgres:9.6
    container_name: "core-hydra-db"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    restart: on-failure
