services:

  oidc:
    container_name: oidc
    hostname: oidc
    image: qlik/simple-oidc-provider
    ports:
      - 9005:9005
    environment:
      REDIRECTS: http://localhost:9002/oidc/callback
      IDP_NAME: http://localhost:9005
      CONFIG_FILE: /var/run/config.json
      USERS_FILE: /var/run/users.json
      PORT: "9005"
    volumes:
      - ./oidc.config.json:/var/run/config.json
      - ./oidc.users.json:/var/run/users.json

  redis:
    image: 'bitnami/redis:latest'
    container_name: "core-redis"
    env_file:
      - redis.env
    ports:
      - "6379:6379"
    restart: on-failure

  hydra_migrate:
    image: oryd/hydra:v1.10.2
    container_name: "core-hydra-migrate"
    volumes:
      - ./hydra.yaml:/var/run/config.yaml:ro
      - ./hydra.custom.yaml:/var/run/config.custom.yaml:ro
    command:
      - migrate
      - sql
      - --yes
      - --read-from-env
      - --config=/var/run/config.yaml,/var/run/config.custom.yaml
    restart: on-failure

  hydra:
    image: oryd/hydra:v1.10.2
    container_name: "core-hydra"
    ports:
      - "4444:4444"
      - "4445:4445"
    volumes:
      - ./hydra.yaml:/var/run/config.yaml:ro
      - ./hydra.custom.yaml:/var/run/config.custom.yaml:ro
    command:
      - serve
      - all
      - --dangerous-force-http
      - --config=/var/run/config.yaml,/var/run/config.custom.yaml
    restart: on-failure

  db:
    image: postgres:9.6
    container_name: "core_db"
    ports:
      - "5433:5432"
    env_file:
      - postgres.env
    volumes:
      - ./webapp.postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
    restart: on-failure
