import { IIconProps } from 'native-base';

import { iconMap } from '../assets/iconMap';

export type IconProps = {
  name: keyof typeof iconMap;
} & Omit<IIconProps, 'name'>;

export enum IconName {
  ATTACHMENT = 'attachment',
  BENEFICIARY = 'beneficiary',
  CALENDAR = 'calendar',
  CALL = 'call',
  CASE = 'case',
  CHAT = 'chat',
  DELETE = 'delete',
  EDIT = 'edit',
  EMAIL = 'email',
  FACE_ERROR = 'faceError',
  FACE_GENERAL = 'faceGeneral',
  FACE_SUCCESS = 'faceSuccess',
  FAVORITE = 'favorite',
  FEMALE = 'female',
  FILTER = 'filter',
  HOME = 'home',
  IMAGE = 'image',
  LOCK = 'lock',
  MALE = 'male',
  MENU = 'menu',
  MORE = 'more',
  NEXT = 'next',
  NOTIFICATION = 'notification',
  PLUS = 'plus',
  PRINT = 'print',
  PROTECTION = 'protection',
  REGISTRATION = 'registration',
  RELOAD = 'reload',
  SAVE = 'save',
  SEARCH = 'search',
  SETTING = 'setting',
  SHARE = 'share',
  SYNC = 'sync',
  THUMBNAIL = 'thumbnail',
  UNLOCK = 'unlock',
  UPLOAD = 'upload',
  USER_ADD = 'userAdd',
  USER_DELETE = 'userDelete',
  USER_GROUP = 'userGroup',
  USER_GROUP_ADD = 'userGroupAdd',
  WHATSAPP = 'whatsapp',
  ACTIVITY_CAMP = 'activityCamp',
  ACTIVITY_EDUCATION = 'activityEducation',
  ACTIVITY_FOOD = 'activityFood',
  ACTIVITY_ICLA = 'activityIcla',
  ACTIVITY_SHELTER = 'activityShelter',
  ACTIVITY_WASH = 'activityWash',
}
