// +build !ignore_autogenerated

// Hello!

// Code generated by defaulter-gen. DO NOT EDIT.

package v1

import (
	runtime "github.com/nrc-no/core/apps/api/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&CustomResourceDefinition{}, func(obj interface{}) { SetObjectDefaults_CustomResourceDefinition(obj.(*CustomResourceDefinition)) })
	scheme.AddTypeDefaultingFunc(&CustomResourceDefinitionList{}, func(obj interface{}) {
		SetObjectDefaults_CustomResourceDefinitionList(obj.(*CustomResourceDefinitionList))
	})
	return nil
}

func SetObjectDefaults_CustomResourceDefinition(in *CustomResourceDefinition) {
	SetDefaults_CustomResourceDefinition(in)
	SetDefaults_CustomResourceDefinitionSpec(&in.Spec)
}

func SetObjectDefaults_CustomResourceDefinitionList(in *CustomResourceDefinitionList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_CustomResourceDefinition(a)
	}
}
