// Hello!

package v1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-generated-swagger-docs.sh

// AUTO-GENERATED FUNCTIONS START HERE. DO NOT EDIT.
var map_ConversionRequest = map[string]string{
	"":                  "ConversionRequest describes the conversion request parameters.",
	"uid":               "uid is an identifier for the individual request/response. It allows distinguishing instances of requests which are otherwise identical (parallel requests, etc). The UID is meant to track the round trip (request/response) between the Kubernetes API server and the webhook, not the user request. It is suitable for correlating log entries between the webhook and apiserver, for either auditing or debugging.",
	"desiredAPIVersion": "desiredAPIVersion is the version to convert given objects to. e.g. \"myapi.example.com/v1\"",
	"objects":           "objects is the list of custom resource objects to be converted.",
}

func (ConversionRequest) SwaggerDoc() map[string]string {
	return map_ConversionRequest
}

var map_ConversionResponse = map[string]string{
	"":                 "ConversionResponse describes a conversion response.",
	"uid":              "uid is an identifier for the individual request/response. This should be copied over from the corresponding `request.uid`.",
	"convertedObjects": "convertedObjects is the list of converted version of `request.objects` if the `result` is successful, otherwise empty. The webhook is expected to set `apiVersion` of these objects to the `request.desiredAPIVersion`. The list must also have the same size as the input list with the same objects in the same order (equal kind, metadata.uid, metadata.name and metadata.namespace). The webhook is allowed to mutate labels and annotations. Any other change to the metadata is silently ignored.",
	"result":           "result contains the result of conversion with extra details if the conversion failed. `result.status` determines if the conversion failed or succeeded. The `result.status` field is required and represents the success or failure of the conversion. A successful conversion must set `result.status` to `Success`. A failed conversion must set `result.status` to `Failure` and provide more details in `result.message` and return http status 200. The `result.message` will be used to construct an error message for the end user.",
}

func (ConversionResponse) SwaggerDoc() map[string]string {
	return map_ConversionResponse
}

var map_ConversionReview = map[string]string{
	"":         "ConversionReview describes a conversion request/response.",
	"request":  "request describes the attributes for the conversion request.",
	"response": "response describes the attributes for the conversion response.",
}

func (ConversionReview) SwaggerDoc() map[string]string {
	return map_ConversionReview
}

var map_CustomResourceColumnDefinition = map[string]string{
	"":            "CustomResourceColumnDefinition specifies a column for server side printing.",
	"name":        "name is a human readable name for the column.",
	"type":        "type is an OpenAPI type definition for this column. See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types for details.",
	"format":      "format is an optional OpenAPI type definition for this column. The 'name' format is applied to the primary identifier column to assist in clients identifying column is the resource name. See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types for details.",
	"description": "description is a human readable description of this column.",
	"priority":    "priority is an integer defining the relative importance of this column compared to others. Lower numbers are considered higher priority. Columns that may be omitted in limited space scenarios should be given a priority greater than 0.",
	"jsonPath":    "jsonPath is a simple JSON path (i.e. with array notation) which is evaluated against each custom resource to produce the value for this column.",
}

func (CustomResourceColumnDefinition) SwaggerDoc() map[string]string {
	return map_CustomResourceColumnDefinition
}

var map_CustomResourceConversion = map[string]string{
	"":         "CustomResourceConversion describes how to convert different versions of a CR.",
	"strategy": "strategy specifies how custom resources are converted between versions. Allowed values are: - `None`: The converter only change the apiVersion and would not touch any other field in the custom resource. - `Webhook`: API Server will call to an external webhook to do the conversion. Additional information\n  is needed for this option. This requires spec.preserveUnknownFields to be false, and spec.conversion.webhook to be set.",
	"webhook":  "webhook describes how to call the conversion webhook. Required when `strategy` is set to `Webhook`.",
}

func (CustomResourceConversion) SwaggerDoc() map[string]string {
	return map_CustomResourceConversion
}

var map_CustomResourceDefinition = map[string]string{
	"":       "CustomResourceDefinition represents a resource that should be exposed on the API server.  Its name MUST be in the format <.spec.name>.<.spec.group>.",
	"spec":   "spec describes how the user wants the resources to appear",
	"status": "status indicates the actual state of the CustomResourceDefinition",
}

func (CustomResourceDefinition) SwaggerDoc() map[string]string {
	return map_CustomResourceDefinition
}

var map_CustomResourceDefinitionCondition = map[string]string{
	"":                   "CustomResourceDefinitionCondition contains details for the current condition of this pod.",
	"type":               "type is the type of the condition. Types include Established, NamesAccepted and Terminating.",
	"status":             "status is the status of the condition. Can be True, False, Unknown.",
	"lastTransitionTime": "lastTransitionTime last time the condition transitioned from one status to another.",
	"reason":             "reason is a unique, one-word, CamelCase reason for the condition's last transition.",
	"message":            "message is a human-readable message indicating details about last transition.",
}

func (CustomResourceDefinitionCondition) SwaggerDoc() map[string]string {
	return map_CustomResourceDefinitionCondition
}

var map_CustomResourceDefinitionList = map[string]string{
	"":      "CustomResourceDefinitionList is a list of CustomResourceDefinition objects.",
	"items": "items list individual CustomResourceDefinition objects",
}

func (CustomResourceDefinitionList) SwaggerDoc() map[string]string {
	return map_CustomResourceDefinitionList
}

var map_CustomResourceDefinitionNames = map[string]string{
	"":           "CustomResourceDefinitionNames indicates the names to serve this CustomResourceDefinition",
	"plural":     "plural is the plural name of the resource to serve. The custom resources are served under `/apis/<group>/<version>/.../<plural>`. Must match the name of the CustomResourceDefinition (in the form `<names.plural>.<group>`). Must be all lowercase.",
	"singular":   "singular is the singular name of the resource. It must be all lowercase. Defaults to lowercased `kind`.",
	"shortNames": "shortNames are short names for the resource, exposed in API discovery documents, and used by clients to support invocations like `kubectl get <shortname>`. It must be all lowercase.",
	"kind":       "kind is the serialized kind of the resource. It is normally CamelCase and singular. Custom resource instances will use this value as the `kind` attribute in API calls.",
	"listKind":   "listKind is the serialized kind of the list for this resource. Defaults to \"`kind`List\".",
	"categories": "categories is a list of grouped resources this custom resource belongs to (e.g. 'all'). This is published in API discovery documents, and used by clients to support invocations like `kubectl get all`.",
}

func (CustomResourceDefinitionNames) SwaggerDoc() map[string]string {
	return map_CustomResourceDefinitionNames
}

var map_CustomResourceDefinitionSpec = map[string]string{
	"":                      "CustomResourceDefinitionSpec describes how a user wants their resource to appear",
	"group":                 "group is the API group of the defined custom resource. The custom resources are served under `/apis/<group>/...`. Must match the name of the CustomResourceDefinition (in the form `<names.plural>.<group>`).",
	"names":                 "names specify the resource and kind names for the custom resource.",
	"scope":                 "scope indicates whether the defined custom resource is cluster- or namespace-scoped. Allowed values are `Cluster` and `Namespaced`.",
	"versions":              "versions is the list of all API versions of the defined custom resource. Version names are used to compute the order in which served versions are listed in API discovery. If the version string is \"kube-like\", it will sort above non \"kube-like\" version strings, which are ordered lexicographically. \"Kube-like\" versions start with a \"v\", then are followed by a number (the major version), then optionally the string \"alpha\" or \"beta\" and another number (the minor version). These are sorted first by GA > beta > alpha (where GA is a version with no suffix such as beta or alpha), and then by comparing major version, then minor version. An example sorted list of versions: v10, v2, v1, v11beta2, v10beta3, v3beta1, v12alpha1, v11alpha2, foo1, foo10.",
	"conversion":            "conversion defines conversion settings for the CRD.",
	"preserveUnknownFields": "preserveUnknownFields indicates that object fields which are not specified in the OpenAPI schema should be preserved when persisting to storage. apiVersion, kind, metadata and known fields inside metadata are always preserved. This field is deprecated in favor of setting `x-preserve-unknown-fields` to true in `spec.versions[*].schema.openAPIV3Schema`. See https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#pruning-versus-preserving-unknown-fields for details.",
}

func (CustomResourceDefinitionSpec) SwaggerDoc() map[string]string {
	return map_CustomResourceDefinitionSpec
}

var map_CustomResourceDefinitionStatus = map[string]string{
	"":               "CustomResourceDefinitionStatus indicates the state of the CustomResourceDefinition",
	"conditions":     "conditions indicate state for particular aspects of a CustomResourceDefinition",
	"acceptedNames":  "acceptedNames are the names that are actually being used to serve discovery. They may be different than the names in spec.",
	"storedVersions": "storedVersions lists all versions of CustomResources that were ever persisted. Tracking these versions allows a migration path for stored versions in etcd. The field is mutable so a migration controller can finish a migration to another version (ensuring no old objects are left in storage), and then remove the rest of the versions from this list. Versions may not be removed from `spec.versions` while they exist in this list.",
}

func (CustomResourceDefinitionStatus) SwaggerDoc() map[string]string {
	return map_CustomResourceDefinitionStatus
}

var map_CustomResourceDefinitionVersion = map[string]string{
	"":                         "CustomResourceDefinitionVersion describes a version for CRD.",
	"name":                     "name is the version name, e.g. “v1”, “v2beta1”, etc. The custom resources are served under this version at `/apis/<group>/<version>/...` if `served` is true.",
	"served":                   "served is a flag enabling/disabling this version from being served via REST APIs",
	"storage":                  "storage indicates this version should be used when persisting custom resources to storage. There must be exactly one version with storage=true.",
	"deprecated":               "deprecated indicates this version of the custom resource API is deprecated. When set to true, API requests to this version receive a warning header in the server response. Defaults to false.",
	"deprecationWarning":       "deprecationWarning overrides the default warning returned to API clients. May only be set when `deprecated` is true. The default warning indicates this version is deprecated and recommends use of the newest served version of equal or greater stability, if one exists.",
	"schema":                   "schema describes the schema used for validation, pruning, and defaulting of this version of the custom resource.",
	"subresources":             "subresources specify what subresources this version of the defined custom resource have.",
	"additionalPrinterColumns": "additionalPrinterColumns specifies additional columns returned in Table output. See https://kubernetes.io/docs/reference/using-api/api-concepts/#receiving-resources-as-tables for details. If no columns are specified, a single column displaying the age of the custom resource is used.",
}

func (CustomResourceDefinitionVersion) SwaggerDoc() map[string]string {
	return map_CustomResourceDefinitionVersion
}

var map_CustomResourceSubresourceScale = map[string]string{
	"":                   "CustomResourceSubresourceScale defines how to serve the scale subresource for CustomResources.",
	"specReplicasPath":   "specReplicasPath defines the JSON path inside of a custom resource that corresponds to Scale `spec.replicas`. Only JSON paths without the array notation are allowed. Must be a JSON Path under `.spec`. If there is no value under the given path in the custom resource, the `/scale` subresource will return an error on GET.",
	"statusReplicasPath": "statusReplicasPath defines the JSON path inside of a custom resource that corresponds to Scale `status.replicas`. Only JSON paths without the array notation are allowed. Must be a JSON Path under `.status`. If there is no value under the given path in the custom resource, the `status.replicas` value in the `/scale` subresource will default to 0.",
	"labelSelectorPath":  "labelSelectorPath defines the JSON path inside of a custom resource that corresponds to Scale `status.selector`. Only JSON paths without the array notation are allowed. Must be a JSON Path under `.status` or `.spec`. Must be set to work with HorizontalPodAutoscaler. The field pointed by this JSON path must be a string field (not a complex selector struct) which contains a serialized label selector in string form. More info: https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions#scale-subresource If there is no value under the given path in the custom resource, the `status.selector` value in the `/scale` subresource will default to the empty string.",
}

func (CustomResourceSubresourceScale) SwaggerDoc() map[string]string {
	return map_CustomResourceSubresourceScale
}

var map_CustomResourceSubresourceStatus = map[string]string{
	"": "CustomResourceSubresourceStatus defines how to serve the status subresource for CustomResources. Status is represented by the `.status` JSON path inside of a CustomResource. When set, * exposes a /status subresource for the custom resource * PUT requests to the /status subresource take a custom resource object, and ignore changes to anything except the status stanza * PUT/POST/PATCH requests to the custom resource ignore changes to the status stanza",
}

func (CustomResourceSubresourceStatus) SwaggerDoc() map[string]string {
	return map_CustomResourceSubresourceStatus
}

var map_CustomResourceSubresources = map[string]string{
	"":       "CustomResourceSubresources defines the status and scale subresources for CustomResources.",
	"status": "status indicates the custom resource should serve a `/status` subresource. When enabled: 1. requests to the custom resource primary endpoint ignore changes to the `status` stanza of the object. 2. requests to the custom resource `/status` subresource ignore changes to anything other than the `status` stanza of the object.",
	"scale":  "scale indicates the custom resource should serve a `/scale` subresource that returns an `autoscaling/v1` Scale object.",
}

func (CustomResourceSubresources) SwaggerDoc() map[string]string {
	return map_CustomResourceSubresources
}

var map_CustomResourceValidation = map[string]string{
	"":                "CustomResourceValidation is a list of validation methods for CustomResources.",
	"openAPIV3Schema": "openAPIV3Schema is the OpenAPI v3 schema to use for validation and pruning.",
}

func (CustomResourceValidation) SwaggerDoc() map[string]string {
	return map_CustomResourceValidation
}

var map_ServiceReference = map[string]string{
	"":          "ServiceReference holds a reference to Service.legacy.k8s.io",
	"namespace": "namespace is the namespace of the service. Required",
	"name":      "name is the name of the service. Required",
	"path":      "path is an optional URL path at which the webhook will be contacted.",
	"port":      "port is an optional service port at which the webhook will be contacted. `port` should be a valid port number (1-65535, inclusive). Defaults to 443 for backward compatibility.",
}

func (ServiceReference) SwaggerDoc() map[string]string {
	return map_ServiceReference
}

var map_WebhookClientConfig = map[string]string{
	"":         "WebhookClientConfig contains the information to make a TLS connection with the webhook.",
	"url":      "url gives the location of the webhook, in standard URL form (`scheme://host:port/path`). Exactly one of `url` or `service` must be specified.\n\nThe `host` should not refer to a service running in the cluster; use the `service` field instead. The host might be resolved via external DNS in some apiservers (e.g., `kube-apiserver` cannot resolve in-cluster DNS as that would be a layering violation). `host` may also be an IP address.\n\nPlease note that using `localhost` or `127.0.0.1` as a `host` is risky unless you take great care to run this webhook on all hosts which run an apiserver which might need to make calls to this webhook. Such installs are likely to be non-portable, i.e., not easy to turn up in a new cluster.\n\nThe scheme must be \"https\"; the URL must begin with \"https://\".\n\nA path is optional, and if present may be any string permissible in a URL. You may use the path to pass an arbitrary string to the webhook, for example, a cluster identifier.\n\nAttempting to use a user or basic auth e.g. \"user:password@\" is not allowed. Fragments (\"#...\") and query parameters (\"?...\") are not allowed, either.",
	"service":  "service is a reference to the service for this webhook. Either service or url must be specified.\n\nIf the webhook is running within the cluster, then you should use `service`.",
	"caBundle": "caBundle is a PEM encoded CA bundle which will be used to validate the webhook's server certificate. If unspecified, system trust roots on the apiserver are used.",
}

func (WebhookClientConfig) SwaggerDoc() map[string]string {
	return map_WebhookClientConfig
}

var map_WebhookConversion = map[string]string{
	"":                         "WebhookConversion describes how to call a conversion webhook",
	"clientConfig":             "clientConfig is the instructions for how to call the webhook if strategy is `Webhook`.",
	"conversionReviewVersions": "conversionReviewVersions is an ordered list of preferred `ConversionReview` versions the Webhook expects. The API server will use the first version in the list which it supports. If none of the versions specified in this list are supported by API server, conversion will fail for the custom resource. If a persisted Webhook configuration specifies allowed versions and does not include any versions known to the API Server, calls to the webhook will fail.",
}

func (WebhookConversion) SwaggerDoc() map[string]string {
	return map_WebhookConversion
}

// AUTO-GENERATED FUNCTIONS END HERE
