#!/bin/bash
#
# increase maximum open files for shell to workaround issue on Fedora
ulimit -n 1000000
# When run as a hook by git, DIR be the repository's root folder.
DIR=$(pwd)

PREFIX="[pre-push]"

echo "$PREFIX Running hook..."

#
# CHECK FOR RUNNING CONTAINERS
#
echo "$PREFIX Checking docker-compose..."
cd artifacts || exit
if [ -w "$(which docker-compose)" ]; then
  DC="docker-compose ps"
else
  DC="sudo docker-compose ps"
fi
CONTAINERS=('hydra_1' 'hydra_db_1' 'hydra_migrate' 'mongo-express' 'mongo_1' 'redis')
for c in "${CONTAINERS[@]}"; do
  if ! (eval "$DC" | grep -q "$c" &>/dev/null); then
    echo "$PREFIX Please ensure docker-compose is up and running."
    exit 1
  fi
done
echo "$PREFIX All containers are up and running!"

#
# RUN E2E TESTS
#

# check for localhost:9000 listening
#
echo "$PREFIX Checking webapp"
serverIsRunning() {
  netstat -tln | grep -q ":9000" &>/dev/null
  return $?
}
if ! serverIsRunning; then
  echo "$PREFIX webapp is not running, attempting to start it now."
  cd "$DIR/api" || exit
  make serve &>/dev/null &

  n=0
  until [ "$n" -ge 5 ]; do
    serverIsRunning && break
    n=$((n + 1))
    sleep 10
  done

  if ! serverIsRunning; then
    echo >&2 "$PREFIX Unable to start webapp."
    exit 1
  fi
fi
echo "$PREFIX webapp is up and running!"

cd "$DIR/e2e" || exit

# linting
#
echo "$PREFIX Running eslint on .js files..."
if ! npm run lint:fix; then
  echo >&2 "[pre-push] Linting failed, see output above."
  exit 1
fi

echo "$PREFIX Running E2E tests..."
if ! npm run run; then
  echo >&2 "[pre-push] E2E tests failed, see output above."
  exit 1
fi
echo "$PREFIX All E2E tests passed!"

#
# RUN INTEGRATION TESTS
#
echo "$PREFIX Running IAM integration tests..."

cd "$DIR/api/pkg/apps/iam" || exit
export GO111MODULE=on
if ! go test; then
  echo >&2 "[pre-push] Integration tests failed, see output above."
  exit 1
fi

echo "$PREFIX Running CMS integration tests..."

cd "$DIR/api/pkg/apps/cms" || exit
if ! go test; then
  echo >&2 "[pre-push] Integration tests failed, see output above."
  exit 1
fi

exit 0
