// Code generated by "stringer -type=ValueKind"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ValueKindNull-0]
	_ = x[ValueKindInt-1]
	_ = x[ValueKindFloat-2]
	_ = x[ValueKindString-3]
	_ = x[ValueKindBool-4]
}

const _ValueKind_name = "ValueKindNullValueKindIntValueKindFloatValueKindStringValueKindBool"

var _ValueKind_index = [...]uint8{0, 13, 25, 39, 54, 67}

func (i ValueKind) String() string {
	if i >= ValueKind(len(_ValueKind_index)-1) {
		return "ValueKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValueKind_name[_ValueKind_index[i]:_ValueKind_index[i+1]]
}
