// +build !ignore_autogenerated

// Hello!

// Code generated by conversion-gen. DO NOT EDIT.

package testscheme

import (
	url "net/url"

	conversion "github.com/nrc-no/core/apps/api/pkg/conversion"
	runtime "github.com/nrc-no/core/apps/api/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*url.Values)(nil), (*TestModelUrlValues)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_url_Values_To_testscheme_TestModelUrlValues(a.(*url.Values), b.(*TestModelUrlValues), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_url_Values_To_testscheme_TestModelUrlValues(in *url.Values, out *TestModelUrlValues, s conversion.Scope) error {
	// WARNING: Field TypeMeta does not have json tag, skipping.

	if values, ok := map[string][]string(*in)["abc"]; ok && len(values) > 0 {
		if err := runtime.Convert_Slice_string_To_string(&values, &out.Abc, s); err != nil {
			return err
		}
	} else {
		out.Abc = ""
	}
	return nil
}

// Convert_url_Values_To_testscheme_TestModelUrlValues is an autogenerated conversion function.
func Convert_url_Values_To_testscheme_TestModelUrlValues(in *url.Values, out *TestModelUrlValues, s conversion.Scope) error {
	return autoConvert_url_Values_To_testscheme_TestModelUrlValues(in, out, s)
}
