// +build !ignore_autogenerated

// Hello!

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	core "github.com/nrc-no/core/apps/api/pkg/apis/core"

	conversion "github.com/nrc-no/core/apps/api/pkg/conversion"
	runtime "github.com/nrc-no/core/apps/api/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*CustomResourceNames)(nil), (*core.CustomResourceNames)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_CustomResourceNames_To_core_CustomResourceNames(a.(*CustomResourceNames), b.(*core.CustomResourceNames), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.CustomResourceNames)(nil), (*CustomResourceNames)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_CustomResourceNames_To_CustomResourceNames(a.(*core.CustomResourceNames), b.(*CustomResourceNames), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FormDefinition)(nil), (*core.FormDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_FormDefinition_To_core_FormDefinition(a.(*FormDefinition), b.(*core.FormDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormDefinition)(nil), (*FormDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormDefinition_To_FormDefinition(a.(*core.FormDefinition), b.(*FormDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FormDefinitionList)(nil), (*core.FormDefinitionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_FormDefinitionList_To_core_FormDefinitionList(a.(*FormDefinitionList), b.(*core.FormDefinitionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormDefinitionList)(nil), (*FormDefinitionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormDefinitionList_To_FormDefinitionList(a.(*core.FormDefinitionList), b.(*FormDefinitionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FormDefinitionSpec)(nil), (*core.FormDefinitionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_FormDefinitionSpec_To_core_FormDefinitionSpec(a.(*FormDefinitionSpec), b.(*core.FormDefinitionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormDefinitionSpec)(nil), (*FormDefinitionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormDefinitionSpec_To_FormDefinitionSpec(a.(*core.FormDefinitionSpec), b.(*FormDefinitionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FormDefinitionVersion)(nil), (*core.FormDefinitionVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_FormDefinitionVersion_To_core_FormDefinitionVersion(a.(*FormDefinitionVersion), b.(*core.FormDefinitionVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormDefinitionVersion)(nil), (*FormDefinitionVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormDefinitionVersion_To_FormDefinitionVersion(a.(*core.FormDefinitionVersion), b.(*FormDefinitionVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FormElement)(nil), (*core.FormElement)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_FormElement_To_core_FormElement(a.(*FormElement), b.(*core.FormElement), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormElement)(nil), (*FormElement)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormElement_To_FormElement(a.(*core.FormElement), b.(*FormElement), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FormSchema)(nil), (*core.FormSchema)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_FormSchema_To_core_FormSchema(a.(*FormSchema), b.(*core.FormSchema), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormSchema)(nil), (*FormSchema)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormSchema_To_FormSchema(a.(*core.FormSchema), b.(*FormSchema), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FormSchemaDefinition)(nil), (*core.FormSchemaDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_FormSchemaDefinition_To_core_FormSchemaDefinition(a.(*FormSchemaDefinition), b.(*core.FormSchemaDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormSchemaDefinition)(nil), (*FormSchemaDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormSchemaDefinition_To_FormSchemaDefinition(a.(*core.FormSchemaDefinition), b.(*FormSchemaDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TranslatedString)(nil), (*core.TranslatedString)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_TranslatedString_To_core_TranslatedString(a.(*TranslatedString), b.(*core.TranslatedString), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.TranslatedString)(nil), (*TranslatedString)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_TranslatedString_To_TranslatedString(a.(*core.TranslatedString), b.(*TranslatedString), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_CustomResourceNames_To_core_CustomResourceNames(in *CustomResourceNames, out *core.CustomResourceNames, s conversion.Scope) error {
	out.Plural = in.Plural
	out.Singular = in.Singular
	out.Kind = in.Kind
	return nil
}

// Convert_CustomResourceNames_To_core_CustomResourceNames is an autogenerated conversion function.
func Convert_CustomResourceNames_To_core_CustomResourceNames(in *CustomResourceNames, out *core.CustomResourceNames, s conversion.Scope) error {
	return autoConvert_CustomResourceNames_To_core_CustomResourceNames(in, out, s)
}

func autoConvert_core_CustomResourceNames_To_CustomResourceNames(in *core.CustomResourceNames, out *CustomResourceNames, s conversion.Scope) error {
	out.Plural = in.Plural
	out.Singular = in.Singular
	out.Kind = in.Kind
	return nil
}

// Convert_core_CustomResourceNames_To_CustomResourceNames is an autogenerated conversion function.
func Convert_core_CustomResourceNames_To_CustomResourceNames(in *core.CustomResourceNames, out *CustomResourceNames, s conversion.Scope) error {
	return autoConvert_core_CustomResourceNames_To_CustomResourceNames(in, out, s)
}

func autoConvert_FormDefinition_To_core_FormDefinition(in *FormDefinition, out *core.FormDefinition, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_FormDefinitionSpec_To_core_FormDefinitionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_FormDefinition_To_core_FormDefinition is an autogenerated conversion function.
func Convert_FormDefinition_To_core_FormDefinition(in *FormDefinition, out *core.FormDefinition, s conversion.Scope) error {
	return autoConvert_FormDefinition_To_core_FormDefinition(in, out, s)
}

func autoConvert_core_FormDefinition_To_FormDefinition(in *core.FormDefinition, out *FormDefinition, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_core_FormDefinitionSpec_To_FormDefinitionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_FormDefinition_To_FormDefinition is an autogenerated conversion function.
func Convert_core_FormDefinition_To_FormDefinition(in *core.FormDefinition, out *FormDefinition, s conversion.Scope) error {
	return autoConvert_core_FormDefinition_To_FormDefinition(in, out, s)
}

func autoConvert_FormDefinitionList_To_core_FormDefinitionList(in *FormDefinitionList, out *core.FormDefinitionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.TypeMeta = in.TypeMeta
	out.Items = *(*[]core.FormDefinition)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_FormDefinitionList_To_core_FormDefinitionList is an autogenerated conversion function.
func Convert_FormDefinitionList_To_core_FormDefinitionList(in *FormDefinitionList, out *core.FormDefinitionList, s conversion.Scope) error {
	return autoConvert_FormDefinitionList_To_core_FormDefinitionList(in, out, s)
}

func autoConvert_core_FormDefinitionList_To_FormDefinitionList(in *core.FormDefinitionList, out *FormDefinitionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.TypeMeta = in.TypeMeta
	out.Items = *(*[]FormDefinition)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_core_FormDefinitionList_To_FormDefinitionList is an autogenerated conversion function.
func Convert_core_FormDefinitionList_To_FormDefinitionList(in *core.FormDefinitionList, out *FormDefinitionList, s conversion.Scope) error {
	return autoConvert_core_FormDefinitionList_To_FormDefinitionList(in, out, s)
}

func autoConvert_FormDefinitionSpec_To_core_FormDefinitionSpec(in *FormDefinitionSpec, out *core.FormDefinitionSpec, s conversion.Scope) error {
	out.Group = in.Group
	if err := Convert_CustomResourceNames_To_core_CustomResourceNames(&in.Names, &out.Names, s); err != nil {
		return err
	}
	out.Versions = *(*[]core.FormDefinitionVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_FormDefinitionSpec_To_core_FormDefinitionSpec is an autogenerated conversion function.
func Convert_FormDefinitionSpec_To_core_FormDefinitionSpec(in *FormDefinitionSpec, out *core.FormDefinitionSpec, s conversion.Scope) error {
	return autoConvert_FormDefinitionSpec_To_core_FormDefinitionSpec(in, out, s)
}

func autoConvert_core_FormDefinitionSpec_To_FormDefinitionSpec(in *core.FormDefinitionSpec, out *FormDefinitionSpec, s conversion.Scope) error {
	out.Group = in.Group
	if err := Convert_core_CustomResourceNames_To_CustomResourceNames(&in.Names, &out.Names, s); err != nil {
		return err
	}
	out.Versions = *(*[]FormDefinitionVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_core_FormDefinitionSpec_To_FormDefinitionSpec is an autogenerated conversion function.
func Convert_core_FormDefinitionSpec_To_FormDefinitionSpec(in *core.FormDefinitionSpec, out *FormDefinitionSpec, s conversion.Scope) error {
	return autoConvert_core_FormDefinitionSpec_To_FormDefinitionSpec(in, out, s)
}

func autoConvert_FormDefinitionVersion_To_core_FormDefinitionVersion(in *FormDefinitionVersion, out *core.FormDefinitionVersion, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_FormSchema_To_core_FormSchema(&in.Schema, &out.Schema, s); err != nil {
		return err
	}
	return nil
}

// Convert_FormDefinitionVersion_To_core_FormDefinitionVersion is an autogenerated conversion function.
func Convert_FormDefinitionVersion_To_core_FormDefinitionVersion(in *FormDefinitionVersion, out *core.FormDefinitionVersion, s conversion.Scope) error {
	return autoConvert_FormDefinitionVersion_To_core_FormDefinitionVersion(in, out, s)
}

func autoConvert_core_FormDefinitionVersion_To_FormDefinitionVersion(in *core.FormDefinitionVersion, out *FormDefinitionVersion, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_core_FormSchema_To_FormSchema(&in.Schema, &out.Schema, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_FormDefinitionVersion_To_FormDefinitionVersion is an autogenerated conversion function.
func Convert_core_FormDefinitionVersion_To_FormDefinitionVersion(in *core.FormDefinitionVersion, out *FormDefinitionVersion, s conversion.Scope) error {
	return autoConvert_core_FormDefinitionVersion_To_FormDefinitionVersion(in, out, s)
}

func autoConvert_FormElement_To_core_FormElement(in *FormElement, out *core.FormElement, s conversion.Scope) error {
	out.Key = in.Key
	out.ID = in.ID
	out.Name = *(*[]core.TranslatedString)(unsafe.Pointer(&in.Name))
	out.Type = in.Type
	out.Description = *(*[]core.TranslatedString)(unsafe.Pointer(&in.Description))
	out.Children = *(*[]core.FormElement)(unsafe.Pointer(&in.Children))
	return nil
}

// Convert_FormElement_To_core_FormElement is an autogenerated conversion function.
func Convert_FormElement_To_core_FormElement(in *FormElement, out *core.FormElement, s conversion.Scope) error {
	return autoConvert_FormElement_To_core_FormElement(in, out, s)
}

func autoConvert_core_FormElement_To_FormElement(in *core.FormElement, out *FormElement, s conversion.Scope) error {
	out.Key = in.Key
	out.ID = in.ID
	out.Name = *(*[]TranslatedString)(unsafe.Pointer(&in.Name))
	out.Type = in.Type
	out.Description = *(*[]TranslatedString)(unsafe.Pointer(&in.Description))
	out.Children = *(*[]FormElement)(unsafe.Pointer(&in.Children))
	return nil
}

// Convert_core_FormElement_To_FormElement is an autogenerated conversion function.
func Convert_core_FormElement_To_FormElement(in *core.FormElement, out *FormElement, s conversion.Scope) error {
	return autoConvert_core_FormElement_To_FormElement(in, out, s)
}

func autoConvert_FormSchema_To_core_FormSchema(in *FormSchema, out *core.FormSchema, s conversion.Scope) error {
	if err := Convert_FormSchemaDefinition_To_core_FormSchemaDefinition(&in.FormSchema, &out.FormSchema, s); err != nil {
		return err
	}
	return nil
}

// Convert_FormSchema_To_core_FormSchema is an autogenerated conversion function.
func Convert_FormSchema_To_core_FormSchema(in *FormSchema, out *core.FormSchema, s conversion.Scope) error {
	return autoConvert_FormSchema_To_core_FormSchema(in, out, s)
}

func autoConvert_core_FormSchema_To_FormSchema(in *core.FormSchema, out *FormSchema, s conversion.Scope) error {
	if err := Convert_core_FormSchemaDefinition_To_FormSchemaDefinition(&in.FormSchema, &out.FormSchema, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_FormSchema_To_FormSchema is an autogenerated conversion function.
func Convert_core_FormSchema_To_FormSchema(in *core.FormSchema, out *FormSchema, s conversion.Scope) error {
	return autoConvert_core_FormSchema_To_FormSchema(in, out, s)
}

func autoConvert_FormSchemaDefinition_To_core_FormSchemaDefinition(in *FormSchemaDefinition, out *core.FormSchemaDefinition, s conversion.Scope) error {
	if err := Convert_FormElement_To_core_FormElement(&in.Root, &out.Root, s); err != nil {
		return err
	}
	return nil
}

// Convert_FormSchemaDefinition_To_core_FormSchemaDefinition is an autogenerated conversion function.
func Convert_FormSchemaDefinition_To_core_FormSchemaDefinition(in *FormSchemaDefinition, out *core.FormSchemaDefinition, s conversion.Scope) error {
	return autoConvert_FormSchemaDefinition_To_core_FormSchemaDefinition(in, out, s)
}

func autoConvert_core_FormSchemaDefinition_To_FormSchemaDefinition(in *core.FormSchemaDefinition, out *FormSchemaDefinition, s conversion.Scope) error {
	if err := Convert_core_FormElement_To_FormElement(&in.Root, &out.Root, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_FormSchemaDefinition_To_FormSchemaDefinition is an autogenerated conversion function.
func Convert_core_FormSchemaDefinition_To_FormSchemaDefinition(in *core.FormSchemaDefinition, out *FormSchemaDefinition, s conversion.Scope) error {
	return autoConvert_core_FormSchemaDefinition_To_FormSchemaDefinition(in, out, s)
}

func autoConvert_TranslatedString_To_core_TranslatedString(in *TranslatedString, out *core.TranslatedString, s conversion.Scope) error {
	out.Locale = in.Locale
	out.Value = in.Value
	return nil
}

// Convert_TranslatedString_To_core_TranslatedString is an autogenerated conversion function.
func Convert_TranslatedString_To_core_TranslatedString(in *TranslatedString, out *core.TranslatedString, s conversion.Scope) error {
	return autoConvert_TranslatedString_To_core_TranslatedString(in, out, s)
}

func autoConvert_core_TranslatedString_To_TranslatedString(in *core.TranslatedString, out *TranslatedString, s conversion.Scope) error {
	out.Locale = in.Locale
	out.Value = in.Value
	return nil
}

// Convert_core_TranslatedString_To_TranslatedString is an autogenerated conversion function.
func Convert_core_TranslatedString_To_TranslatedString(in *core.TranslatedString, out *TranslatedString, s conversion.Scope) error {
	return autoConvert_core_TranslatedString_To_TranslatedString(in, out, s)
}
