// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "github.com/nrc-no/core/apps/api/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceNames) DeepCopyInto(out *CustomResourceNames) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceNames.
func (in *CustomResourceNames) DeepCopy() *CustomResourceNames {
	if in == nil {
		return nil
	}
	out := new(CustomResourceNames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormDefinition) DeepCopyInto(out *FormDefinition) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormDefinition.
func (in *FormDefinition) DeepCopy() *FormDefinition {
	if in == nil {
		return nil
	}
	out := new(FormDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FormDefinition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormDefinitionList) DeepCopyInto(out *FormDefinitionList) {
	*out = *in
	out.ListMeta = in.ListMeta
	out.TypeMeta = in.TypeMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FormDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormDefinitionList.
func (in *FormDefinitionList) DeepCopy() *FormDefinitionList {
	if in == nil {
		return nil
	}
	out := new(FormDefinitionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FormDefinitionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormDefinitionSpec) DeepCopyInto(out *FormDefinitionSpec) {
	*out = *in
	out.Names = in.Names
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]FormDefinitionVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormDefinitionSpec.
func (in *FormDefinitionSpec) DeepCopy() *FormDefinitionSpec {
	if in == nil {
		return nil
	}
	out := new(FormDefinitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormDefinitionVersion) DeepCopyInto(out *FormDefinitionVersion) {
	*out = *in
	in.Schema.DeepCopyInto(&out.Schema)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormDefinitionVersion.
func (in *FormDefinitionVersion) DeepCopy() *FormDefinitionVersion {
	if in == nil {
		return nil
	}
	out := new(FormDefinitionVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormElement) DeepCopyInto(out *FormElement) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = make([]TranslatedString, len(*in))
		copy(*out, *in)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = make([]TranslatedString, len(*in))
		copy(*out, *in)
	}
	if in.Children != nil {
		in, out := &in.Children, &out.Children
		*out = make([]FormElement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormElement.
func (in *FormElement) DeepCopy() *FormElement {
	if in == nil {
		return nil
	}
	out := new(FormElement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormSchema) DeepCopyInto(out *FormSchema) {
	*out = *in
	in.FormSchema.DeepCopyInto(&out.FormSchema)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormSchema.
func (in *FormSchema) DeepCopy() *FormSchema {
	if in == nil {
		return nil
	}
	out := new(FormSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormSchemaDefinition) DeepCopyInto(out *FormSchemaDefinition) {
	*out = *in
	in.Root.DeepCopyInto(&out.Root)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormSchemaDefinition.
func (in *FormSchemaDefinition) DeepCopy() *FormSchemaDefinition {
	if in == nil {
		return nil
	}
	out := new(FormSchemaDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TranslatedString) DeepCopyInto(out *TranslatedString) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TranslatedString.
func (in *TranslatedString) DeepCopy() *TranslatedString {
	if in == nil {
		return nil
	}
	out := new(TranslatedString)
	in.DeepCopyInto(out)
	return out
}
