// +build !ignore_autogenerated

// Hello!

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	core "github.com/nrc-no/core/apps/api/pkg/apis/core"
	v1 "github.com/nrc-no/core/apps/api/pkg/apis/core/v1"
	conversion "github.com/nrc-no/core/apps/api/pkg/conversion"
	runtime "github.com/nrc-no/core/apps/api/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*v1.CustomResourceNames)(nil), (*core.CustomResourceNames)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CustomResourceNames_To_core_CustomResourceNames(a.(*v1.CustomResourceNames), b.(*core.CustomResourceNames), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.CustomResourceNames)(nil), (*v1.CustomResourceNames)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_CustomResourceNames_To_v1_CustomResourceNames(a.(*core.CustomResourceNames), b.(*v1.CustomResourceNames), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.FormDefinition)(nil), (*core.FormDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FormDefinition_To_core_FormDefinition(a.(*v1.FormDefinition), b.(*core.FormDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormDefinition)(nil), (*v1.FormDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormDefinition_To_v1_FormDefinition(a.(*core.FormDefinition), b.(*v1.FormDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.FormDefinitionList)(nil), (*core.FormDefinitionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FormDefinitionList_To_core_FormDefinitionList(a.(*v1.FormDefinitionList), b.(*core.FormDefinitionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormDefinitionList)(nil), (*v1.FormDefinitionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormDefinitionList_To_v1_FormDefinitionList(a.(*core.FormDefinitionList), b.(*v1.FormDefinitionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.FormDefinitionSpec)(nil), (*core.FormDefinitionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FormDefinitionSpec_To_core_FormDefinitionSpec(a.(*v1.FormDefinitionSpec), b.(*core.FormDefinitionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormDefinitionSpec)(nil), (*v1.FormDefinitionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormDefinitionSpec_To_v1_FormDefinitionSpec(a.(*core.FormDefinitionSpec), b.(*v1.FormDefinitionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.FormDefinitionVersion)(nil), (*core.FormDefinitionVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FormDefinitionVersion_To_core_FormDefinitionVersion(a.(*v1.FormDefinitionVersion), b.(*core.FormDefinitionVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormDefinitionVersion)(nil), (*v1.FormDefinitionVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormDefinitionVersion_To_v1_FormDefinitionVersion(a.(*core.FormDefinitionVersion), b.(*v1.FormDefinitionVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.FormElement)(nil), (*core.FormElement)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FormElement_To_core_FormElement(a.(*v1.FormElement), b.(*core.FormElement), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormElement)(nil), (*v1.FormElement)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormElement_To_v1_FormElement(a.(*core.FormElement), b.(*v1.FormElement), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.FormSchema)(nil), (*core.FormSchema)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FormSchema_To_core_FormSchema(a.(*v1.FormSchema), b.(*core.FormSchema), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormSchema)(nil), (*v1.FormSchema)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormSchema_To_v1_FormSchema(a.(*core.FormSchema), b.(*v1.FormSchema), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.FormSchemaDefinition)(nil), (*core.FormSchemaDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FormSchemaDefinition_To_core_FormSchemaDefinition(a.(*v1.FormSchemaDefinition), b.(*core.FormSchemaDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.FormSchemaDefinition)(nil), (*v1.FormSchemaDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_FormSchemaDefinition_To_v1_FormSchemaDefinition(a.(*core.FormSchemaDefinition), b.(*v1.FormSchemaDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.TranslatedString)(nil), (*core.TranslatedString)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_TranslatedString_To_core_TranslatedString(a.(*v1.TranslatedString), b.(*core.TranslatedString), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.TranslatedString)(nil), (*v1.TranslatedString)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_TranslatedString_To_v1_TranslatedString(a.(*core.TranslatedString), b.(*v1.TranslatedString), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_CustomResourceNames_To_core_CustomResourceNames(in *v1.CustomResourceNames, out *core.CustomResourceNames, s conversion.Scope) error {
	out.Plural = in.Plural
	out.Singular = in.Singular
	out.Kind = in.Kind
	return nil
}

// Convert_v1_CustomResourceNames_To_core_CustomResourceNames is an autogenerated conversion function.
func Convert_v1_CustomResourceNames_To_core_CustomResourceNames(in *v1.CustomResourceNames, out *core.CustomResourceNames, s conversion.Scope) error {
	return autoConvert_v1_CustomResourceNames_To_core_CustomResourceNames(in, out, s)
}

func autoConvert_core_CustomResourceNames_To_v1_CustomResourceNames(in *core.CustomResourceNames, out *v1.CustomResourceNames, s conversion.Scope) error {
	out.Plural = in.Plural
	out.Singular = in.Singular
	out.Kind = in.Kind
	return nil
}

// Convert_core_CustomResourceNames_To_v1_CustomResourceNames is an autogenerated conversion function.
func Convert_core_CustomResourceNames_To_v1_CustomResourceNames(in *core.CustomResourceNames, out *v1.CustomResourceNames, s conversion.Scope) error {
	return autoConvert_core_CustomResourceNames_To_v1_CustomResourceNames(in, out, s)
}

func autoConvert_v1_FormDefinition_To_core_FormDefinition(in *v1.FormDefinition, out *core.FormDefinition, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_FormDefinitionSpec_To_core_FormDefinitionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_FormDefinition_To_core_FormDefinition is an autogenerated conversion function.
func Convert_v1_FormDefinition_To_core_FormDefinition(in *v1.FormDefinition, out *core.FormDefinition, s conversion.Scope) error {
	return autoConvert_v1_FormDefinition_To_core_FormDefinition(in, out, s)
}

func autoConvert_core_FormDefinition_To_v1_FormDefinition(in *core.FormDefinition, out *v1.FormDefinition, s conversion.Scope) error {
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_core_FormDefinitionSpec_To_v1_FormDefinitionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_FormDefinition_To_v1_FormDefinition is an autogenerated conversion function.
func Convert_core_FormDefinition_To_v1_FormDefinition(in *core.FormDefinition, out *v1.FormDefinition, s conversion.Scope) error {
	return autoConvert_core_FormDefinition_To_v1_FormDefinition(in, out, s)
}

func autoConvert_v1_FormDefinitionList_To_core_FormDefinitionList(in *v1.FormDefinitionList, out *core.FormDefinitionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.TypeMeta = in.TypeMeta
	out.Items = *(*[]core.FormDefinition)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_FormDefinitionList_To_core_FormDefinitionList is an autogenerated conversion function.
func Convert_v1_FormDefinitionList_To_core_FormDefinitionList(in *v1.FormDefinitionList, out *core.FormDefinitionList, s conversion.Scope) error {
	return autoConvert_v1_FormDefinitionList_To_core_FormDefinitionList(in, out, s)
}

func autoConvert_core_FormDefinitionList_To_v1_FormDefinitionList(in *core.FormDefinitionList, out *v1.FormDefinitionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.TypeMeta = in.TypeMeta
	out.Items = *(*[]v1.FormDefinition)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_core_FormDefinitionList_To_v1_FormDefinitionList is an autogenerated conversion function.
func Convert_core_FormDefinitionList_To_v1_FormDefinitionList(in *core.FormDefinitionList, out *v1.FormDefinitionList, s conversion.Scope) error {
	return autoConvert_core_FormDefinitionList_To_v1_FormDefinitionList(in, out, s)
}

func autoConvert_v1_FormDefinitionSpec_To_core_FormDefinitionSpec(in *v1.FormDefinitionSpec, out *core.FormDefinitionSpec, s conversion.Scope) error {
	out.Group = in.Group
	if err := Convert_v1_CustomResourceNames_To_core_CustomResourceNames(&in.Names, &out.Names, s); err != nil {
		return err
	}
	out.Versions = *(*[]core.FormDefinitionVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_v1_FormDefinitionSpec_To_core_FormDefinitionSpec is an autogenerated conversion function.
func Convert_v1_FormDefinitionSpec_To_core_FormDefinitionSpec(in *v1.FormDefinitionSpec, out *core.FormDefinitionSpec, s conversion.Scope) error {
	return autoConvert_v1_FormDefinitionSpec_To_core_FormDefinitionSpec(in, out, s)
}

func autoConvert_core_FormDefinitionSpec_To_v1_FormDefinitionSpec(in *core.FormDefinitionSpec, out *v1.FormDefinitionSpec, s conversion.Scope) error {
	out.Group = in.Group
	if err := Convert_core_CustomResourceNames_To_v1_CustomResourceNames(&in.Names, &out.Names, s); err != nil {
		return err
	}
	out.Versions = *(*[]v1.FormDefinitionVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_core_FormDefinitionSpec_To_v1_FormDefinitionSpec is an autogenerated conversion function.
func Convert_core_FormDefinitionSpec_To_v1_FormDefinitionSpec(in *core.FormDefinitionSpec, out *v1.FormDefinitionSpec, s conversion.Scope) error {
	return autoConvert_core_FormDefinitionSpec_To_v1_FormDefinitionSpec(in, out, s)
}

func autoConvert_v1_FormDefinitionVersion_To_core_FormDefinitionVersion(in *v1.FormDefinitionVersion, out *core.FormDefinitionVersion, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_v1_FormSchema_To_core_FormSchema(&in.Schema, &out.Schema, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_FormDefinitionVersion_To_core_FormDefinitionVersion is an autogenerated conversion function.
func Convert_v1_FormDefinitionVersion_To_core_FormDefinitionVersion(in *v1.FormDefinitionVersion, out *core.FormDefinitionVersion, s conversion.Scope) error {
	return autoConvert_v1_FormDefinitionVersion_To_core_FormDefinitionVersion(in, out, s)
}

func autoConvert_core_FormDefinitionVersion_To_v1_FormDefinitionVersion(in *core.FormDefinitionVersion, out *v1.FormDefinitionVersion, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_core_FormSchema_To_v1_FormSchema(&in.Schema, &out.Schema, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_FormDefinitionVersion_To_v1_FormDefinitionVersion is an autogenerated conversion function.
func Convert_core_FormDefinitionVersion_To_v1_FormDefinitionVersion(in *core.FormDefinitionVersion, out *v1.FormDefinitionVersion, s conversion.Scope) error {
	return autoConvert_core_FormDefinitionVersion_To_v1_FormDefinitionVersion(in, out, s)
}

func autoConvert_v1_FormElement_To_core_FormElement(in *v1.FormElement, out *core.FormElement, s conversion.Scope) error {
	out.Key = in.Key
	out.ID = in.ID
	out.Name = *(*[]core.TranslatedString)(unsafe.Pointer(&in.Name))
	out.Type = in.Type
	out.Description = *(*[]core.TranslatedString)(unsafe.Pointer(&in.Description))
	out.Children = *(*[]core.FormElement)(unsafe.Pointer(&in.Children))
	return nil
}

// Convert_v1_FormElement_To_core_FormElement is an autogenerated conversion function.
func Convert_v1_FormElement_To_core_FormElement(in *v1.FormElement, out *core.FormElement, s conversion.Scope) error {
	return autoConvert_v1_FormElement_To_core_FormElement(in, out, s)
}

func autoConvert_core_FormElement_To_v1_FormElement(in *core.FormElement, out *v1.FormElement, s conversion.Scope) error {
	out.Key = in.Key
	out.ID = in.ID
	out.Name = *(*[]v1.TranslatedString)(unsafe.Pointer(&in.Name))
	out.Type = in.Type
	out.Description = *(*[]v1.TranslatedString)(unsafe.Pointer(&in.Description))
	out.Children = *(*[]v1.FormElement)(unsafe.Pointer(&in.Children))
	return nil
}

// Convert_core_FormElement_To_v1_FormElement is an autogenerated conversion function.
func Convert_core_FormElement_To_v1_FormElement(in *core.FormElement, out *v1.FormElement, s conversion.Scope) error {
	return autoConvert_core_FormElement_To_v1_FormElement(in, out, s)
}

func autoConvert_v1_FormSchema_To_core_FormSchema(in *v1.FormSchema, out *core.FormSchema, s conversion.Scope) error {
	if err := Convert_v1_FormSchemaDefinition_To_core_FormSchemaDefinition(&in.FormSchema, &out.FormSchema, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_FormSchema_To_core_FormSchema is an autogenerated conversion function.
func Convert_v1_FormSchema_To_core_FormSchema(in *v1.FormSchema, out *core.FormSchema, s conversion.Scope) error {
	return autoConvert_v1_FormSchema_To_core_FormSchema(in, out, s)
}

func autoConvert_core_FormSchema_To_v1_FormSchema(in *core.FormSchema, out *v1.FormSchema, s conversion.Scope) error {
	if err := Convert_core_FormSchemaDefinition_To_v1_FormSchemaDefinition(&in.FormSchema, &out.FormSchema, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_FormSchema_To_v1_FormSchema is an autogenerated conversion function.
func Convert_core_FormSchema_To_v1_FormSchema(in *core.FormSchema, out *v1.FormSchema, s conversion.Scope) error {
	return autoConvert_core_FormSchema_To_v1_FormSchema(in, out, s)
}

func autoConvert_v1_FormSchemaDefinition_To_core_FormSchemaDefinition(in *v1.FormSchemaDefinition, out *core.FormSchemaDefinition, s conversion.Scope) error {
	if err := Convert_v1_FormElement_To_core_FormElement(&in.Root, &out.Root, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_FormSchemaDefinition_To_core_FormSchemaDefinition is an autogenerated conversion function.
func Convert_v1_FormSchemaDefinition_To_core_FormSchemaDefinition(in *v1.FormSchemaDefinition, out *core.FormSchemaDefinition, s conversion.Scope) error {
	return autoConvert_v1_FormSchemaDefinition_To_core_FormSchemaDefinition(in, out, s)
}

func autoConvert_core_FormSchemaDefinition_To_v1_FormSchemaDefinition(in *core.FormSchemaDefinition, out *v1.FormSchemaDefinition, s conversion.Scope) error {
	if err := Convert_core_FormElement_To_v1_FormElement(&in.Root, &out.Root, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_FormSchemaDefinition_To_v1_FormSchemaDefinition is an autogenerated conversion function.
func Convert_core_FormSchemaDefinition_To_v1_FormSchemaDefinition(in *core.FormSchemaDefinition, out *v1.FormSchemaDefinition, s conversion.Scope) error {
	return autoConvert_core_FormSchemaDefinition_To_v1_FormSchemaDefinition(in, out, s)
}

func autoConvert_v1_TranslatedString_To_core_TranslatedString(in *v1.TranslatedString, out *core.TranslatedString, s conversion.Scope) error {
	out.Locale = in.Locale
	out.Value = in.Value
	return nil
}

// Convert_v1_TranslatedString_To_core_TranslatedString is an autogenerated conversion function.
func Convert_v1_TranslatedString_To_core_TranslatedString(in *v1.TranslatedString, out *core.TranslatedString, s conversion.Scope) error {
	return autoConvert_v1_TranslatedString_To_core_TranslatedString(in, out, s)
}

func autoConvert_core_TranslatedString_To_v1_TranslatedString(in *core.TranslatedString, out *v1.TranslatedString, s conversion.Scope) error {
	out.Locale = in.Locale
	out.Value = in.Value
	return nil
}

// Convert_core_TranslatedString_To_v1_TranslatedString is an autogenerated conversion function.
func Convert_core_TranslatedString_To_v1_TranslatedString(in *core.TranslatedString, out *v1.TranslatedString, s conversion.Scope) error {
	return autoConvert_core_TranslatedString_To_v1_TranslatedString(in, out, s)
}
