import * as icons from './icons';

export const iconMap = {
  activityCamp: icons.ActivityCamp,
  activityEducation: icons.ActivityEducation,
  activityFood: icons.ActivityFood,
  activityIcla: icons.ActivityIcla,
  activityShelter: icons.ActivityShelter,
  activityWash: icons.ActivityWash,
  attachment: icons.Attachment,
  arrowDown: icons.ArrowDown,
  arrowLeft: icons.ArrowLeft,
  arrowRight: icons.ArrowRight,
  arrowUp: icons.ArrowUp,
  beneficiary: icons.Beneficiary,
  calendar: icons.Calendar,
  case: icons.Case,
  circleError: icons.CircleError,
  circleSuccess: icons.CircleSuccess,
  circleQuestion: icons.CircleQuestion,
  delete: icons.Delete,
  edit: icons.Edit,
  email: icons.Email,
  faceError: icons.FaceError,
  faceGeneral: icons.FaceGeneral,
  faceSuccess: icons.FaceSuccess,
  filter: icons.Filter,
  home: icons.Home,
  menu: icons.Menu,
  minus: icons.Minus,
  more: icons.More,
  next: icons.Next,
  notification: icons.Notification,
  plus: icons.Plus,
  protection: icons.Protection,
  registration: icons.Registration,
  reload: icons.Reload,
  save: icons.Save,
  search: icons.Search,
  setting: icons.Setting,
  sync: icons.Sync,
  thumbnail: icons.Thumbnail,
  upload: icons.Upload,
};
