serve:
  admin:
    host: "127.0.0.1"
    port: "9001"
    urls:
      self: http://localhost:9001
    oidc:
      issuer: https://dev-53701279.okta.com
      clientid: 0oa2c2ul49JMRlP375d7
      scopes:
        - openid
        - email
        - profile
  public:
    host: "127.0.0.1"
    port: "9000"
    urls:
      self: http://localhost:9000
    oidc:
      issuer: http://localhost:4444/
      client_id: public
  login:
    host: "127.0.0.1"
    port: "9002"
    urls:
      self: http://localhost:9002
