log:
  level: info
serve:
  admin:
    host: "0.0.0.0"
    port: "9001"
    tls:
      enabled: true
      cert:
        path: creds/core/admin_api/tls.crt
      key:
        path: creds/core/admin_api/tls.key
    urls:
      self: https://core.dev:8443
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:3001
      allow_credentials: true
      allowed_headers:
        - Authorization
        - Content-Type
        - Accept
      allowed_methods:
        - "GET"
        - "POST"
        - "PUT"
        - "OPTIONS"
        - "DELETE"
      debug: true
      exposed_headers:
        - Location
    cache:
      redis:
        address: localhost:6379
        max_idle_connections: 10
        max_length: 65536
  public:
    host: "0.0.0.0"
    port: "9000"
    tls:
      enabled: true
      cert:
        path: creds/core/api/tls.crt
      key:
        path: creds/core/api/tls.key
    urls:
      self: https://core.dev:8080
    cache:
      redis:
        address: localhost:6379
        max_idle_connections: 10
        max_length: 65536
    cors:
      allowed_origins:
        - https://localhost:3000
      allow_credentials: true
      allowed_headers:
        - Authorization
        - Content-Type
        - Accept
      allowed_methods:
        - "GET"
        - "POST"
        - "PUT"
        - "OPTIONS"
        - "DELETE"
      debug: true
      enabled: true
      exposed_headers:
        - Location
  login:
    host: "127.0.0.1"
    port: "9002"
    tls:
      enabled: true
      cert:
        path: creds/core/login/tls.crt
      key:
        path: creds/core/login/tls.key
    urls:
      self: https://core.dev:8443/login
    cache:
      redis:
        address: localhost:6379
        max_idle_connections: 10
        max_length: 65536
  auth:
    host: "127.0.0.1"
    port: "9004"
    tls:
      enabled: true
      cert:
        path: creds/core/auth/tls.crt
      key:
        path: creds/core/auth/tls.key
    urls:
      self: https://core.dev:8443
    cors:
      allowed_origins:
        - https://localhost:3001
      allow_credentials: true
      allowed_headers:
        - Authorization
        - Content-Type
        - Accept
      allowed_methods:
        - "GET"
        - "POST"
        - "PUT"
        - "OPTIONS"
        - "DELETE"
      debug: true
      enabled: true
      exposed_headers:
        - Location
hydra:
  admin:
    host: core.dev:8443
    base_path: hydra-admin/
    schemes:
      - https
  public:
    host: core.dev:8443
    base_path: hydra/
    schemes:
      - https
