log:
  # Possible values are (debug, info, warn, error, dpanic, panic, fatal)
  level: info


serve:
  admin:

    # Admin server serving address
    host: "0.0.0.0"
    # Admin server serving port
    port: "9001"


    # Admin server TLS options
    tls:
      enabled: false

    urls:
      # Address where the server can be publicly accessed
      self: http://localhost:9001


    oidc:
      # Oauth2 callback URL
      redirect_uri: http://localhost:9001/oidc/callback
      # OAuth2 required scopes
      scopes:
        - openid
        - profile
        - email
      # Default redirect after oauth flow
      post_login_default_redirect_uri: http://localhost:3001
      # Authorized redirect URIs after oauth flow
      post_login_allowed_redirect_uris:
        - http://localhost:3001
        - http://localhost:3001/
        - http://localhost:3001/session-renew
        - http://localhost:3001/session-renew/

    # CORS settings
    cors:
      # Enable/Disable CORS
      enabled: true
      # Cors Allowed-Origins header config
      allowed_origins:
        - http://localhost:3001
      # Allow credentials in CORS
      allow_credentials: true
      # Allowed CORS headers
      allowed_headers:
        - Authorization
        - Content-Type
        - Accept
      # Allowed CORS methods
      allowed_methods:
        - "GET"
        - "POST"
        - "PUT"
        - "OPTIONS"
        - "DELETE"
      # Print debug information on CORS
      debug: true
      # Exposed CORS headers
      exposed_headers:
        - Location


    # Cache settings
    cache:
      redis:
        # Redis address
        address: localhost:6379
        # Redis max idle connections
        max_idle_connections: 10
        # Redis cache max body length
        max_length: 65536


  public:


    host: "0.0.0.0"
    port: "9000"


    tls:
      enabled: false

    urls:
      self: http://localhost:9000


    oidc:
      # Redirect URI for OAuth2 Callback
      redirect_uri: http://localhost:9000/oidc/callback
      # OAuth2 Scopes
      scopes:
        - openid
        - profile
        - email
      # Default redirect after oauth flow
      post_login_default_redirect_uri: http://localhost:3000
      # Authorized redirect URIs after oauth flow
      post_login_allowed_redirect_uris:
        - http://localhost:3000
        - http://localhost:3000/
        - http://localhost:3000/session-renew
        - http://localhost:3000/session-renew/


    cache:
      redis:
        address: localhost:6379
        max_idle_connections: 10
        max_length: 65536


    cors:
      allowed_origins:
        - http://localhost:3000
      allow_credentials: true
      allowed_headers:
        - Authorization
        - Content-Type
        - Accept
      allowed_methods:
        - "GET"
        - "POST"
        - "PUT"
        - "OPTIONS"
        - "DELETE"
      debug: true
      enabled: true
      exposed_headers:
        - Location


  login:
    host: "127.0.0.1"
    port: "9002"
    tls:
      enabled: false
    urls:
      self: http://localhost:9002
    cache:
      redis:
        address: localhost:6379
        max_idle_connections: 10
        max_length: 65536


hydra:
  admin:
    host: localhost:4445
    schemes:
      - http
