serve:
  admin:
    host: "127.0.0.1"
    port: "9001"
    urls:
      self: "http://localhost:9001"
    cors:
      allowed_origins: [ "http://localhost:3001" ]
      allowed_headers:
        - Authorization
        - Content-Type
      allowed_methods:
        - "GET"
        - "POST"
        - "PUT"
        - "OPTIONS"
        - "DELETE"
      debug: true
      enabled: true
    oidc:
      issuer: http://localhost:9005
      clientid: core-admin
    cache:
      redis:
        address: localhost:6379
        max_idle_connections: 10
        max_length: 65536
  public:
    host: "127.0.0.1"
    port: "9000"
    urls:
      self: http://localhost:9000
    oidc:
      issuer: http://localhost:4444/
      client_id: public
    cache:
      redis:
        address: localhost:6379
        max_idle_connections: 10
        max_length: 65536
  login:
    host: "127.0.0.1"
    port: "9002"
    urls:
      self: http://localhost:9002
    cache:
      redis:
        address: localhost:6379
        max_idle_connections: 10
        max_length: 65536
