serve:
  admin:
    host: "127.0.0.1"
    port: "9001"
    urls:
      self: "http://localhost:9001"
    cors:
      allowed_origins: ["http://localhost:3001"]
      allowed_headers:
        - Authorization
        - Content-Type
      allowed_methods:
        - "GET"
        - "POST"
        - "PUT"
        - "OPTIONS"
        - "DELETE"
      debug: true
      enabled: true
    oidc:
      issuer: https://dev-53701279.okta.com
      clientid: 0oa2gb25jhuFDIkhd5d7
  public:
    host: "127.0.0.1"
    port: "9000"
    urls:
      self: http://127.0.0.1:9000
    oidc:
      issuer: http://127.0.0.1:4444/
      client_id: public
    cors:
      allowed_origins: ["*"]
      allowed_headers:
        - Authorization
        - Content-Type
      allowed_methods:
        - "GET"
        - "POST"
        - "PUT"
        - "OPTIONS"
        - "DELETE"
      debug: true
      enabled: true
  login:
    host: "127.0.0.1"
    port: "9002"
    urls:
      self: http://localhost:9002
