version: '3.1'

services:

  mongo:
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    restart: on-failure

  hydra_migrate:
    image: oryd/hydra:v1.10.2
    command:
      - migrate
      - sql
      - --yes
      - postgres://hydra:secret@hydra_db:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    restart: on-failure

  hydra:
    image: oryd/hydra:v1.10.2
    ports:
      - 4444:4444
      - 4445:4445
    command:
      - serve
      - all
      - --dangerous-force-http
    environment:
      - DSN=postgres://hydra:secret@hydra_db:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - SECRETS_SYSTEM=fVuJ0N1nFuymQjcnC4OWcIyo15gb0MYe
      - URLS_SELF_ISSUER=http://localhost:4444
      - URLS_CONSENT=http://localhost:9000/auth/consent
      - URLS_LOGIN=http://localhost:9000/auth/login
      - URLS_LOGOUT=http://localhost:9000/auth/logout
    restart: on-failure

  hydra_db:
    image: postgres:9.6
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    restart: on-failure
