version: '3.2'
services:
  webapp:
    build: ../
    environment:
      - PORT=9000
  cypress:
    image: "cypress/included:7.5.0"
    depends_on:
      - webapp
    environment:
      - CYPRESS_baseUrl=http://webapp:9000
    volumes:
      - ./:/e2e
