domain: nrc-no.github.io
url: https://nrc-no.github.io
baseUrl: /core/
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  README.md
  CONTRIBUTING.md
  ARCHITECTURE.md

