root = "."
tmp_dir = "tmp"

[build]
  cmd = "make build"
  bin = "tmp/main"
  full_bin = "tmp/main --mongo-database=core --mongo-username=root --mongo-password=example --mongo-hosts=localhost:27017 --redis-address=localhost:6379 --environment=Development --fresh=true --seed=true --tls-disable=true --hydra-admin-url=http://localhost:4445 --hydra-public-url=http://localhost:4444 --login-templates-directory=pkg/apps/login/templates --login-client-id=login --login-client-name=login --login-client-secret=somesecret --login-iam-host=localhost:9000 --login-iam-scheme=http --web-templates-directory=pkg/apps/webapp/templates --web-client-id=webapp --web-client-secret=webapp --web-client-name=webapp --web-iam-host=localhost:9000 --web-iam-scheme=http --web-cms-host=localhost:9000 --web-cms-scheme=http --listen-address=:9000 --base-url=http://localhost:9000"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  include_dir = ["pkg/apps/attachments", "pkg/apps/cms", "pkg/apps/iam", "pkg/apps/login", "pkg/apps/login/templates", "pkg/apps/seeder", "pkg/apps/webapp", "pkg/apps/webapp/templates"]
  include_ext = ["go", "gohtml"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
