version: '3.1'

services:

  mongo:
    network_mode: host
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    network_mode: host
    image: mongo-express
    restart: on-failure
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  redis:
    image: 'bitnami/redis:latest'
    network_mode: host
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    restart: on-failure

  hydra_migrate:
    image: oryd/hydra:v1.10.2
    network_mode: host
    command:
      - migrate
      - sql
      - --yes
      - postgres://hydra:secret@localhost:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    restart: on-failure

  hydra:
    image: oryd/hydra:v1.10.2
    network_mode: host
    ports:
      - 4444:4444
      - 4445:4445
    command:
      - serve
      - all
    volumes:
      - ../api/certs/cert.pem:/certs/cert.pem
      - ../api/certs/key.pem:/certs/key.pem
    environment:
      - DSN=postgres://hydra:secret@localhost:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - SECRETS_SYSTEM=fVuJ0N1nFuymQjcnC4OWcIyo15gb0MYe
      - URLS_SELF_ISSUER=https://localhost:4444
      - URLS_CONSENT=https://localhost:9002/auth/consent
      - URLS_LOGIN=https://localhost:9002/auth/login
      - URLS_LOGOUT=https://localhost:9002/auth/logout
      - LOG_LEAK_SENSITIVE_VALUES=true
      - SERVE_TLS_KEY_PATH=/certs/key.pem
      - SERVE_TLS_CERT_PATH=/certs/cert.pem
      - HTTPS_TLS_KEY_PATH=/certs/key.pem
      - HTTPS_TLS_CERT_PATH=/certs/cert.pem
    restart: on-failure

  hydra_db:
    image: postgres:9.6
    network_mode: host
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    restart: on-failure

  api:
    network_mode: host
    build:
      context: ../api/
      dockerfile: Dockerfile
    ports:
      - 9002:9002
    restart: on-failure
    volumes:
    - ../api/certs/cert.pem:/certs/cert.pem
    - ../api/certs/key.pem:/certs/key.pem
    command:
      - /main
      - --mongo-database=core
      - --mongo-username=root
      - --mongo-password=example
      - --mongo-hosts=localhost:27017
      - --redis-address=redis:6379
      - --redis-password=
      - --redis-network=tcp
      - --redis-secret-key=secret
      - --redis-max-idle-conns=10
      - --environment=Development
      - --fresh=true
      - --seed=true
      - --hydra-admin-url=https://localhost:4445
      - --hydra-public-url=https://localhost:4444
      - --login-client-id=login
      - --login-client-name=login
      - --login-client-secret=somesecret
      - --login-iam-host=localhost:9002
      - --login-iam-scheme=http
      - --login-templates-directory=/static/login/templates
      - --web-client-id=webapp
      - --web-client-secret=webapp
      - --web-client-name=webapp
      - --web-iam-host=localhost:9002
      - --web-iam-scheme=http
      - --web-cms-host=localhost:9002
      - --web-cms-scheme=http
      - --web-templates-directory=/static/webapp/templates
      - --listen-address=:9002
      - --base-url=http://localhost:9002
      - --tls-cert-path=/certs/cert.pem
      - --tls-key-path=/certs/key.pem
